// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CancelPurchaseData,
  CancelPurchaseErrors,
  CancelPurchaseResponses,
  CancelSaleData,
  CancelSaleErrors,
  CancelSaleResponses,
  CreateCategoryData,
  CreateCategoryErrors,
  CreateCategoryResponses,
  CreateProductData,
  CreateProductErrors,
  CreateProductResponses,
  CreatePurchaseData,
  CreatePurchaseErrors,
  CreatePurchaseResponses,
  CreateSaleData,
  CreateSaleErrors,
  CreateSaleResponses,
  CreateSupplierData,
  CreateSupplierErrors,
  CreateSupplierResponses,
  CreateUnityOfMeasureData,
  CreateUnityOfMeasureErrors,
  CreateUnityOfMeasureResponses,
  DeleteCategoryData,
  DeleteCategoryErrors,
  DeleteCategoryResponses,
  DeleteProductData,
  DeleteProductErrors,
  DeleteProductResponses,
  DeleteSupplierData,
  DeleteSupplierErrors,
  DeleteSupplierResponses,
  DeleteUnityOfMeasureData,
  DeleteUnityOfMeasureErrors,
  DeleteUnityOfMeasureResponses,
  GetApiAuthManageInfoData,
  GetApiAuthManageInfoErrors,
  GetApiAuthManageInfoResponses,
  GetCategoriesData,
  GetCategoriesLookupData,
  GetCategoriesLookupResponses,
  GetCategoriesResponses,
  GetCategoryByIdData,
  GetCategoryByIdErrors,
  GetCategoryByIdResponses,
  GetFinancialSummaryData,
  GetFinancialSummaryResponses,
  GetLotByIdData,
  GetLotByIdErrors,
  GetLotByIdResponses,
  GetLotsByProductData,
  GetLotsByProductResponses,
  GetLotsByPurchaseData,
  GetLotsByPurchaseResponses,
  GetLotsData,
  GetLotsResponses,
  GetProductByIdData,
  GetProductByIdErrors,
  GetProductByIdResponses,
  GetProductsByCategoryData,
  GetProductsByCategoryResponses,
  GetProductsByUnityOfMeasureData,
  GetProductsByUnityOfMeasureResponses,
  GetProductsData,
  GetProductsLookupData,
  GetProductsLookupResponses,
  GetProductsResponses,
  GetPurchaseByIdData,
  GetPurchaseByIdErrors,
  GetPurchaseByIdResponses,
  GetPurchasesBySupplierData,
  GetPurchasesBySupplierResponses,
  GetPurchasesData,
  GetPurchasesResponses,
  GetRecentTransactionsData,
  GetRecentTransactionsResponses,
  GetSaleByIdData,
  GetSaleByIdErrors,
  GetSaleByIdResponses,
  GetSaleDetailsBySaleData,
  GetSaleDetailsBySaleResponses,
  GetSalesData,
  GetSalesResponses,
  GetSupplierByIdData,
  GetSupplierByIdErrors,
  GetSupplierByIdResponses,
  GetSuppliersData,
  GetSuppliersLookupData,
  GetSuppliersLookupResponses,
  GetSuppliersResponses,
  GetUnitsOfMeasureData,
  GetUnitsOfMeasureLookupData,
  GetUnitsOfMeasureLookupResponses,
  GetUnitsOfMeasureResponses,
  GetUnityOfMeasureByIdData,
  GetUnityOfMeasureByIdErrors,
  GetUnityOfMeasureByIdResponses,
  GetUserData,
  GetUserErrors,
  GetUserResponses,
  MapIdentityApiApiAuthConfirmEmailData,
  MapIdentityApiApiAuthConfirmEmailResponses,
  PostApiAuthForgotPasswordData,
  PostApiAuthForgotPasswordErrors,
  PostApiAuthForgotPasswordResponses,
  PostApiAuthLoginData,
  PostApiAuthLoginResponses,
  PostApiAuthManage2FaData,
  PostApiAuthManage2FaErrors,
  PostApiAuthManage2FaResponses,
  PostApiAuthManageInfoData,
  PostApiAuthManageInfoErrors,
  PostApiAuthManageInfoResponses,
  PostApiAuthRefreshData,
  PostApiAuthRefreshResponses,
  PostApiAuthRegisterData,
  PostApiAuthRegisterErrors,
  PostApiAuthRegisterResponses,
  PostApiAuthResendConfirmationEmailData,
  PostApiAuthResendConfirmationEmailResponses,
  PostApiAuthResetPasswordData,
  PostApiAuthResetPasswordErrors,
  PostApiAuthResetPasswordResponses,
  UpdateCategoryData,
  UpdateCategoryErrors,
  UpdateCategoryResponses,
  UpdateProductData,
  UpdateProductErrors,
  UpdateProductResponses,
  UpdateSupplierData,
  UpdateSupplierErrors,
  UpdateSupplierResponses,
  UpdateUnityOfMeasureData,
  UpdateUnityOfMeasureErrors,
  UpdateUnityOfMeasureResponses,
} from "./types.gen";
import {
  zCancelPurchasePath,
  zCancelSalePath,
  zCreateCategoryBody,
  zCreateProductBody,
  zCreatePurchaseBody,
  zCreateSaleBody,
  zCreateSupplierBody,
  zCreateUnityOfMeasureBody,
  zDeleteCategoryPath,
  zDeleteProductPath,
  zDeleteSupplierPath,
  zDeleteUnityOfMeasurePath,
  zGetCategoriesQuery,
  zGetCategoryByIdPath,
  zGetFinancialSummaryQuery,
  zGetLotByIdPath,
  zGetLotsByProductPath,
  zGetLotsByProductQuery,
  zGetLotsByPurchasePath,
  zGetLotsByPurchaseQuery,
  zGetLotsQuery,
  zGetProductByIdPath,
  zGetProductsByCategoryPath,
  zGetProductsByCategoryQuery,
  zGetProductsByUnityOfMeasurePath,
  zGetProductsByUnityOfMeasureQuery,
  zGetProductsQuery,
  zGetPurchaseByIdPath,
  zGetPurchasesBySupplierPath,
  zGetPurchasesBySupplierQuery,
  zGetPurchasesQuery,
  zGetRecentTransactionsQuery,
  zGetSaleByIdPath,
  zGetSaleDetailsBySalePath,
  zGetSaleDetailsBySaleQuery,
  zGetSalesQuery,
  zGetSupplierByIdPath,
  zGetSuppliersQuery,
  zGetUnitsOfMeasureQuery,
  zGetUnityOfMeasureByIdPath,
  zMapIdentityApiApiAuthConfirmEmailQuery,
  zPostApiAuthForgotPasswordBody,
  zPostApiAuthLoginBody,
  zPostApiAuthLoginQuery,
  zPostApiAuthManage2FaBody,
  zPostApiAuthManageInfoBody,
  zPostApiAuthRefreshBody,
  zPostApiAuthRegisterBody,
  zPostApiAuthResendConfirmationEmailBody,
  zPostApiAuthResetPasswordBody,
  zUpdateCategoryBody,
  zUpdateCategoryPath,
  zUpdateProductBody,
  zUpdateProductPath,
  zUpdateSupplierBody,
  zUpdateSupplierPath,
  zUpdateUnityOfMeasureBody,
  zUpdateUnityOfMeasurePath,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const postApiAuthRegister = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthRegisterData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAuthRegisterResponses,
    PostApiAuthRegisterErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiAuthRegisterBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postApiAuthLogin = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthLoginData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAuthLoginResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiAuthLoginBody,
          path: z.never().optional(),
          query: zPostApiAuthLoginQuery.optional(),
        })
        .parseAsync(data),
    url: "/api/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postApiAuthRefresh = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthRefreshData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAuthRefreshResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiAuthRefreshBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/auth/refresh",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const mapIdentityApiApiAuthConfirmEmail = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MapIdentityApiApiAuthConfirmEmailData, ThrowOnError>
) =>
  (options.client ?? client).get<
    MapIdentityApiApiAuthConfirmEmailResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zMapIdentityApiApiAuthConfirmEmailQuery,
        })
        .parseAsync(data),
    url: "/api/auth/confirmEmail",
    ...options,
  });

export const postApiAuthResendConfirmationEmail = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiAuthResendConfirmationEmailData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAuthResendConfirmationEmailResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiAuthResendConfirmationEmailBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/auth/resendConfirmationEmail",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postApiAuthForgotPassword = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthForgotPasswordData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAuthForgotPasswordResponses,
    PostApiAuthForgotPasswordErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiAuthForgotPasswordBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/auth/forgotPassword",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postApiAuthResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthResetPasswordData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAuthResetPasswordResponses,
    PostApiAuthResetPasswordErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiAuthResetPasswordBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/auth/resetPassword",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postApiAuthManage2Fa = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthManage2FaData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAuthManage2FaResponses,
    PostApiAuthManage2FaErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiAuthManage2FaBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/auth/manage/2fa",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getApiAuthManageInfo = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAuthManageInfoData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiAuthManageInfoResponses,
    GetApiAuthManageInfoErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/auth/manage/info",
    ...options,
  });

export const postApiAuthManageInfo = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthManageInfoData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAuthManageInfoResponses,
    PostApiAuthManageInfoErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiAuthManageInfoBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/auth/manage/info",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getUser = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetUserResponses,
    GetUserErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/auth/me",
    ...options,
  });

export const getProducts = <ThrowOnError extends boolean = false>(
  options: Options<GetProductsData, ThrowOnError>
) =>
  (options.client ?? client).get<GetProductsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zGetProductsQuery,
        })
        .parseAsync(data),
    url: "/api/products",
    ...options,
  });

export const createProduct = <ThrowOnError extends boolean = false>(
  options: Options<CreateProductData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateProductResponses,
    CreateProductErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateProductBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/products",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deleteProduct = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProductData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteProductResponses,
    DeleteProductErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zDeleteProductPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/products/{id}",
    ...options,
  });

export const getProductById = <ThrowOnError extends boolean = false>(
  options: Options<GetProductByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetProductByIdResponses,
    GetProductByIdErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetProductByIdPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/products/{id}",
    ...options,
  });

export const updateProduct = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProductData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateProductResponses,
    UpdateProductErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zUpdateProductBody,
          path: zUpdateProductPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/products/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getLotsByProduct = <ThrowOnError extends boolean = false>(
  options: Options<GetLotsByProductData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetLotsByProductResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetLotsByProductPath,
          query: zGetLotsByProductQuery,
        })
        .parseAsync(data),
    url: "/api/products/{id}/lots",
    ...options,
  });

export const getProductsLookup = <ThrowOnError extends boolean = false>(
  options?: Options<GetProductsLookupData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetProductsLookupResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/products/lookup",
    ...options,
  });

export const getCategories = <ThrowOnError extends boolean = false>(
  options: Options<GetCategoriesData, ThrowOnError>
) =>
  (options.client ?? client).get<GetCategoriesResponses, unknown, ThrowOnError>(
    {
      requestValidator: async (data) =>
        await z
          .object({
            body: z.never().optional(),
            path: z.never().optional(),
            query: zGetCategoriesQuery,
          })
          .parseAsync(data),
      url: "/api/categories",
      ...options,
    }
  );

export const createCategory = <ThrowOnError extends boolean = false>(
  options: Options<CreateCategoryData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateCategoryResponses,
    CreateCategoryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateCategoryBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/categories",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deleteCategory = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCategoryData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteCategoryResponses,
    DeleteCategoryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zDeleteCategoryPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/categories/{id}",
    ...options,
  });

export const getCategoryById = <ThrowOnError extends boolean = false>(
  options: Options<GetCategoryByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetCategoryByIdResponses,
    GetCategoryByIdErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetCategoryByIdPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/categories/{id}",
    ...options,
  });

export const updateCategory = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCategoryData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateCategoryResponses,
    UpdateCategoryErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zUpdateCategoryBody,
          path: zUpdateCategoryPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/categories/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getProductsByCategory = <ThrowOnError extends boolean = false>(
  options: Options<GetProductsByCategoryData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetProductsByCategoryResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetProductsByCategoryPath,
          query: zGetProductsByCategoryQuery,
        })
        .parseAsync(data),
    url: "/api/categories/{id}/products",
    ...options,
  });

export const getCategoriesLookup = <ThrowOnError extends boolean = false>(
  options?: Options<GetCategoriesLookupData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetCategoriesLookupResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/categories/lookup",
    ...options,
  });

export const getSuppliers = <ThrowOnError extends boolean = false>(
  options: Options<GetSuppliersData, ThrowOnError>
) =>
  (options.client ?? client).get<GetSuppliersResponses, unknown, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zGetSuppliersQuery,
        })
        .parseAsync(data),
    url: "/api/suppliers",
    ...options,
  });

export const createSupplier = <ThrowOnError extends boolean = false>(
  options: Options<CreateSupplierData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateSupplierResponses,
    CreateSupplierErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateSupplierBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/suppliers",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deleteSupplier = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSupplierData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteSupplierResponses,
    DeleteSupplierErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zDeleteSupplierPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/suppliers/{id}",
    ...options,
  });

export const getSupplierById = <ThrowOnError extends boolean = false>(
  options: Options<GetSupplierByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetSupplierByIdResponses,
    GetSupplierByIdErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetSupplierByIdPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/suppliers/{id}",
    ...options,
  });

export const updateSupplier = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSupplierData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateSupplierResponses,
    UpdateSupplierErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zUpdateSupplierBody,
          path: zUpdateSupplierPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/suppliers/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getPurchasesBySupplier = <ThrowOnError extends boolean = false>(
  options: Options<GetPurchasesBySupplierData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetPurchasesBySupplierResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetPurchasesBySupplierPath,
          query: zGetPurchasesBySupplierQuery,
        })
        .parseAsync(data),
    url: "/api/suppliers/{id}/purchases",
    ...options,
  });

export const getSuppliersLookup = <ThrowOnError extends boolean = false>(
  options?: Options<GetSuppliersLookupData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetSuppliersLookupResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/suppliers/lookup",
    ...options,
  });

export const getUnitsOfMeasure = <ThrowOnError extends boolean = false>(
  options: Options<GetUnitsOfMeasureData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetUnitsOfMeasureResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zGetUnitsOfMeasureQuery,
        })
        .parseAsync(data),
    url: "/api/units-of-measure",
    ...options,
  });

export const createUnityOfMeasure = <ThrowOnError extends boolean = false>(
  options: Options<CreateUnityOfMeasureData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateUnityOfMeasureResponses,
    CreateUnityOfMeasureErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateUnityOfMeasureBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/units-of-measure",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deleteUnityOfMeasure = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUnityOfMeasureData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteUnityOfMeasureResponses,
    DeleteUnityOfMeasureErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zDeleteUnityOfMeasurePath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/units-of-measure/{id}",
    ...options,
  });

export const getUnityOfMeasureById = <ThrowOnError extends boolean = false>(
  options: Options<GetUnityOfMeasureByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetUnityOfMeasureByIdResponses,
    GetUnityOfMeasureByIdErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetUnityOfMeasureByIdPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/units-of-measure/{id}",
    ...options,
  });

export const updateUnityOfMeasure = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUnityOfMeasureData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateUnityOfMeasureResponses,
    UpdateUnityOfMeasureErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zUpdateUnityOfMeasureBody,
          path: zUpdateUnityOfMeasurePath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/units-of-measure/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getProductsByUnityOfMeasure = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetProductsByUnityOfMeasureData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetProductsByUnityOfMeasureResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetProductsByUnityOfMeasurePath,
          query: zGetProductsByUnityOfMeasureQuery,
        })
        .parseAsync(data),
    url: "/api/units-of-measure/{id}/products",
    ...options,
  });

export const getUnitsOfMeasureLookup = <ThrowOnError extends boolean = false>(
  options?: Options<GetUnitsOfMeasureLookupData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetUnitsOfMeasureLookupResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/units-of-measure/lookup",
    ...options,
  });

export const getPurchases = <ThrowOnError extends boolean = false>(
  options: Options<GetPurchasesData, ThrowOnError>
) =>
  (options.client ?? client).get<GetPurchasesResponses, unknown, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zGetPurchasesQuery,
        })
        .parseAsync(data),
    url: "/api/purchases",
    ...options,
  });

export const createPurchase = <ThrowOnError extends boolean = false>(
  options: Options<CreatePurchaseData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreatePurchaseResponses,
    CreatePurchaseErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreatePurchaseBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/purchases",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const cancelPurchase = <ThrowOnError extends boolean = false>(
  options: Options<CancelPurchaseData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    CancelPurchaseResponses,
    CancelPurchaseErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zCancelPurchasePath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/purchases/{id}",
    ...options,
  });

export const getPurchaseById = <ThrowOnError extends boolean = false>(
  options: Options<GetPurchaseByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetPurchaseByIdResponses,
    GetPurchaseByIdErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetPurchaseByIdPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/purchases/{id}",
    ...options,
  });

export const getLotsByPurchase = <ThrowOnError extends boolean = false>(
  options: Options<GetLotsByPurchaseData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetLotsByPurchaseResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetLotsByPurchasePath,
          query: zGetLotsByPurchaseQuery,
        })
        .parseAsync(data),
    url: "/api/purchases/{id}/lots",
    ...options,
  });

export const getLots = <ThrowOnError extends boolean = false>(
  options: Options<GetLotsData, ThrowOnError>
) =>
  (options.client ?? client).get<GetLotsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zGetLotsQuery,
        })
        .parseAsync(data),
    url: "/api/lots",
    ...options,
  });

export const getLotById = <ThrowOnError extends boolean = false>(
  options: Options<GetLotByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetLotByIdResponses,
    GetLotByIdErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetLotByIdPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/lots/{id}",
    ...options,
  });

export const getSales = <ThrowOnError extends boolean = false>(
  options: Options<GetSalesData, ThrowOnError>
) =>
  (options.client ?? client).get<GetSalesResponses, unknown, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zGetSalesQuery,
        })
        .parseAsync(data),
    url: "/api/sales",
    ...options,
  });

export const createSale = <ThrowOnError extends boolean = false>(
  options: Options<CreateSaleData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateSaleResponses,
    CreateSaleErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateSaleBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/sales",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const cancelSale = <ThrowOnError extends boolean = false>(
  options: Options<CancelSaleData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    CancelSaleResponses,
    CancelSaleErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zCancelSalePath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/sales/{id}",
    ...options,
  });

export const getSaleById = <ThrowOnError extends boolean = false>(
  options: Options<GetSaleByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetSaleByIdResponses,
    GetSaleByIdErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetSaleByIdPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/sales/{id}",
    ...options,
  });

export const getSaleDetailsBySale = <ThrowOnError extends boolean = false>(
  options: Options<GetSaleDetailsBySaleData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetSaleDetailsBySaleResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetSaleDetailsBySalePath,
          query: zGetSaleDetailsBySaleQuery,
        })
        .parseAsync(data),
    url: "/api/sales/{id}/details",
    ...options,
  });

export const getFinancialSummary = <ThrowOnError extends boolean = false>(
  options: Options<GetFinancialSummaryData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetFinancialSummaryResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zGetFinancialSummaryQuery,
        })
        .parseAsync(data),
    url: "/api/dashboard/summary",
    ...options,
  });

export const getRecentTransactions = <ThrowOnError extends boolean = false>(
  options?: Options<GetRecentTransactionsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetRecentTransactionsResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zGetRecentTransactionsQuery.optional(),
        })
        .parseAsync(data),
    url: "/api/dashboard/recent-transactions",
    ...options,
  });
