// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CancelPurchaseData,
  CancelPurchaseErrors,
  CancelPurchaseResponses,
  CancelSaleData,
  CancelSaleErrors,
  CancelSaleResponses,
  CreateCategoryData,
  CreateCategoryErrors,
  CreateCategoryResponses,
  CreateProductData,
  CreateProductErrors,
  CreateProductResponses,
  CreatePurchaseData,
  CreatePurchaseErrors,
  CreatePurchaseResponses,
  CreateSaleData,
  CreateSaleErrors,
  CreateSaleResponses,
  CreateSupplierData,
  CreateSupplierErrors,
  CreateSupplierResponses,
  CreateUnityOfMeasureData,
  CreateUnityOfMeasureErrors,
  CreateUnityOfMeasureResponses,
  DeleteCategoryData,
  DeleteCategoryErrors,
  DeleteCategoryResponses,
  DeleteProductData,
  DeleteProductErrors,
  DeleteProductResponses,
  DeleteSupplierData,
  DeleteSupplierErrors,
  DeleteSupplierResponses,
  DeleteUnityOfMeasureData,
  DeleteUnityOfMeasureErrors,
  DeleteUnityOfMeasureResponses,
  GetApiAuthManageInfoData,
  GetApiAuthManageInfoErrors,
  GetApiAuthManageInfoResponses,
  GetCategoriesData,
  GetCategoriesLookupData,
  GetCategoriesLookupResponses,
  GetCategoriesResponses,
  GetCategoryByIdData,
  GetCategoryByIdErrors,
  GetCategoryByIdResponses,
  GetLotByIdData,
  GetLotByIdErrors,
  GetLotByIdResponses,
  GetLotsByPurchaseData,
  GetLotsByPurchaseResponses,
  GetLotsData,
  GetLotsResponses,
  GetProductByIdData,
  GetProductByIdErrors,
  GetProductByIdResponses,
  GetProductsByCategoryData,
  GetProductsByCategoryResponses,
  GetProductsByUnityOfMeasureData,
  GetProductsByUnityOfMeasureResponses,
  GetProductsData,
  GetProductsLookupData,
  GetProductsLookupResponses,
  GetProductsResponses,
  GetPurchaseByIdData,
  GetPurchaseByIdErrors,
  GetPurchaseByIdResponses,
  GetPurchasesBySupplierData,
  GetPurchasesBySupplierResponses,
  GetPurchasesData,
  GetPurchasesResponses,
  GetSaleByIdData,
  GetSaleByIdErrors,
  GetSaleByIdResponses,
  GetSaleDetailsBySaleData,
  GetSaleDetailsBySaleResponses,
  GetSalesData,
  GetSalesResponses,
  GetSupplierByIdData,
  GetSupplierByIdErrors,
  GetSupplierByIdResponses,
  GetSuppliersData,
  GetSuppliersLookupData,
  GetSuppliersLookupResponses,
  GetSuppliersResponses,
  GetUnitsOfMeasureData,
  GetUnitsOfMeasureLookupData,
  GetUnitsOfMeasureLookupResponses,
  GetUnitsOfMeasureResponses,
  GetUnityOfMeasureByIdData,
  GetUnityOfMeasureByIdErrors,
  GetUnityOfMeasureByIdResponses,
  GetUserData,
  GetUserErrors,
  GetUserResponses,
  MapIdentityApiApiAuthConfirmEmailData,
  MapIdentityApiApiAuthConfirmEmailResponses,
  PostApiAuthForgotPasswordData,
  PostApiAuthForgotPasswordErrors,
  PostApiAuthForgotPasswordResponses,
  PostApiAuthLoginData,
  PostApiAuthLoginResponses,
  PostApiAuthManage2FaData,
  PostApiAuthManage2FaErrors,
  PostApiAuthManage2FaResponses,
  PostApiAuthManageInfoData,
  PostApiAuthManageInfoErrors,
  PostApiAuthManageInfoResponses,
  PostApiAuthRefreshData,
  PostApiAuthRefreshResponses,
  PostApiAuthRegisterData,
  PostApiAuthRegisterErrors,
  PostApiAuthRegisterResponses,
  PostApiAuthResendConfirmationEmailData,
  PostApiAuthResendConfirmationEmailResponses,
  PostApiAuthResetPasswordData,
  PostApiAuthResetPasswordErrors,
  PostApiAuthResetPasswordResponses,
  UpdateCategoryData,
  UpdateCategoryErrors,
  UpdateCategoryResponses,
  UpdateProductData,
  UpdateProductErrors,
  UpdateProductResponses,
  UpdateSupplierData,
  UpdateSupplierErrors,
  UpdateSupplierResponses,
  UpdateUnityOfMeasureData,
  UpdateUnityOfMeasureErrors,
  UpdateUnityOfMeasureResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const postApiAuthRegister = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthRegisterData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAuthRegisterResponses,
    PostApiAuthRegisterErrors,
    ThrowOnError
  >({
    url: "/api/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postApiAuthLogin = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthLoginData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAuthLoginResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postApiAuthRefresh = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthRefreshData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAuthRefreshResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/auth/refresh",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const mapIdentityApiApiAuthConfirmEmail = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MapIdentityApiApiAuthConfirmEmailData, ThrowOnError>
) =>
  (options.client ?? client).get<
    MapIdentityApiApiAuthConfirmEmailResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/auth/confirmEmail", ...options });

export const postApiAuthResendConfirmationEmail = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiAuthResendConfirmationEmailData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAuthResendConfirmationEmailResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/auth/resendConfirmationEmail",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postApiAuthForgotPassword = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthForgotPasswordData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAuthForgotPasswordResponses,
    PostApiAuthForgotPasswordErrors,
    ThrowOnError
  >({
    url: "/api/auth/forgotPassword",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postApiAuthResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthResetPasswordData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAuthResetPasswordResponses,
    PostApiAuthResetPasswordErrors,
    ThrowOnError
  >({
    url: "/api/auth/resetPassword",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postApiAuthManage2Fa = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthManage2FaData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAuthManage2FaResponses,
    PostApiAuthManage2FaErrors,
    ThrowOnError
  >({
    url: "/api/auth/manage/2fa",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getApiAuthManageInfo = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAuthManageInfoData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiAuthManageInfoResponses,
    GetApiAuthManageInfoErrors,
    ThrowOnError
  >({ url: "/api/auth/manage/info", ...options });

export const postApiAuthManageInfo = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthManageInfoData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostApiAuthManageInfoResponses,
    PostApiAuthManageInfoErrors,
    ThrowOnError
  >({
    url: "/api/auth/manage/info",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getUser = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetUserResponses,
    GetUserErrors,
    ThrowOnError
  >({ url: "/api/auth/me", ...options });

export const getProducts = <ThrowOnError extends boolean = false>(
  options: Options<GetProductsData, ThrowOnError>
) =>
  (options.client ?? client).get<GetProductsResponses, unknown, ThrowOnError>({
    url: "/api/products",
    ...options,
  });

export const createProduct = <ThrowOnError extends boolean = false>(
  options: Options<CreateProductData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateProductResponses,
    CreateProductErrors,
    ThrowOnError
  >({
    url: "/api/products",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deleteProduct = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProductData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteProductResponses,
    DeleteProductErrors,
    ThrowOnError
  >({ url: "/api/products/{id}", ...options });

export const getProductById = <ThrowOnError extends boolean = false>(
  options: Options<GetProductByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetProductByIdResponses,
    GetProductByIdErrors,
    ThrowOnError
  >({ url: "/api/products/{id}", ...options });

export const updateProduct = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProductData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateProductResponses,
    UpdateProductErrors,
    ThrowOnError
  >({
    url: "/api/products/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getProductsLookup = <ThrowOnError extends boolean = false>(
  options?: Options<GetProductsLookupData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetProductsLookupResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/products/lookup", ...options });

export const getCategories = <ThrowOnError extends boolean = false>(
  options: Options<GetCategoriesData, ThrowOnError>
) =>
  (options.client ?? client).get<GetCategoriesResponses, unknown, ThrowOnError>(
    { url: "/api/categories", ...options }
  );

export const createCategory = <ThrowOnError extends boolean = false>(
  options: Options<CreateCategoryData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateCategoryResponses,
    CreateCategoryErrors,
    ThrowOnError
  >({
    url: "/api/categories",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deleteCategory = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCategoryData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteCategoryResponses,
    DeleteCategoryErrors,
    ThrowOnError
  >({ url: "/api/categories/{id}", ...options });

export const getCategoryById = <ThrowOnError extends boolean = false>(
  options: Options<GetCategoryByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetCategoryByIdResponses,
    GetCategoryByIdErrors,
    ThrowOnError
  >({ url: "/api/categories/{id}", ...options });

export const updateCategory = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCategoryData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateCategoryResponses,
    UpdateCategoryErrors,
    ThrowOnError
  >({
    url: "/api/categories/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getProductsByCategory = <ThrowOnError extends boolean = false>(
  options: Options<GetProductsByCategoryData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetProductsByCategoryResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/categories/{id}/products", ...options });

export const getCategoriesLookup = <ThrowOnError extends boolean = false>(
  options?: Options<GetCategoriesLookupData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetCategoriesLookupResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/categories/lookup", ...options });

export const getSuppliers = <ThrowOnError extends boolean = false>(
  options: Options<GetSuppliersData, ThrowOnError>
) =>
  (options.client ?? client).get<GetSuppliersResponses, unknown, ThrowOnError>({
    url: "/api/suppliers",
    ...options,
  });

export const createSupplier = <ThrowOnError extends boolean = false>(
  options: Options<CreateSupplierData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateSupplierResponses,
    CreateSupplierErrors,
    ThrowOnError
  >({
    url: "/api/suppliers",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deleteSupplier = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSupplierData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteSupplierResponses,
    DeleteSupplierErrors,
    ThrowOnError
  >({ url: "/api/suppliers/{id}", ...options });

export const getSupplierById = <ThrowOnError extends boolean = false>(
  options: Options<GetSupplierByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetSupplierByIdResponses,
    GetSupplierByIdErrors,
    ThrowOnError
  >({ url: "/api/suppliers/{id}", ...options });

export const updateSupplier = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSupplierData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateSupplierResponses,
    UpdateSupplierErrors,
    ThrowOnError
  >({
    url: "/api/suppliers/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getPurchasesBySupplier = <ThrowOnError extends boolean = false>(
  options: Options<GetPurchasesBySupplierData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetPurchasesBySupplierResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/suppliers/{id}/purchases", ...options });

export const getSuppliersLookup = <ThrowOnError extends boolean = false>(
  options?: Options<GetSuppliersLookupData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetSuppliersLookupResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/suppliers/lookup", ...options });

export const getUnitsOfMeasure = <ThrowOnError extends boolean = false>(
  options: Options<GetUnitsOfMeasureData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetUnitsOfMeasureResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/units-of-measure", ...options });

export const createUnityOfMeasure = <ThrowOnError extends boolean = false>(
  options: Options<CreateUnityOfMeasureData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateUnityOfMeasureResponses,
    CreateUnityOfMeasureErrors,
    ThrowOnError
  >({
    url: "/api/units-of-measure",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deleteUnityOfMeasure = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUnityOfMeasureData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteUnityOfMeasureResponses,
    DeleteUnityOfMeasureErrors,
    ThrowOnError
  >({ url: "/api/units-of-measure/{id}", ...options });

export const getUnityOfMeasureById = <ThrowOnError extends boolean = false>(
  options: Options<GetUnityOfMeasureByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetUnityOfMeasureByIdResponses,
    GetUnityOfMeasureByIdErrors,
    ThrowOnError
  >({ url: "/api/units-of-measure/{id}", ...options });

export const updateUnityOfMeasure = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUnityOfMeasureData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateUnityOfMeasureResponses,
    UpdateUnityOfMeasureErrors,
    ThrowOnError
  >({
    url: "/api/units-of-measure/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getProductsByUnityOfMeasure = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetProductsByUnityOfMeasureData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetProductsByUnityOfMeasureResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/units-of-measure/{id}/products", ...options });

export const getUnitsOfMeasureLookup = <ThrowOnError extends boolean = false>(
  options?: Options<GetUnitsOfMeasureLookupData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetUnitsOfMeasureLookupResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/units-of-measure/lookup", ...options });

export const getPurchases = <ThrowOnError extends boolean = false>(
  options: Options<GetPurchasesData, ThrowOnError>
) =>
  (options.client ?? client).get<GetPurchasesResponses, unknown, ThrowOnError>({
    url: "/api/purchases",
    ...options,
  });

export const createPurchase = <ThrowOnError extends boolean = false>(
  options: Options<CreatePurchaseData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreatePurchaseResponses,
    CreatePurchaseErrors,
    ThrowOnError
  >({
    url: "/api/purchases",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const cancelPurchase = <ThrowOnError extends boolean = false>(
  options: Options<CancelPurchaseData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    CancelPurchaseResponses,
    CancelPurchaseErrors,
    ThrowOnError
  >({ url: "/api/purchases/{id}", ...options });

export const getPurchaseById = <ThrowOnError extends boolean = false>(
  options: Options<GetPurchaseByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetPurchaseByIdResponses,
    GetPurchaseByIdErrors,
    ThrowOnError
  >({ url: "/api/purchases/{id}", ...options });

export const getLotsByPurchase = <ThrowOnError extends boolean = false>(
  options: Options<GetLotsByPurchaseData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetLotsByPurchaseResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/purchases/{id}/lots", ...options });

export const getLots = <ThrowOnError extends boolean = false>(
  options: Options<GetLotsData, ThrowOnError>
) =>
  (options.client ?? client).get<GetLotsResponses, unknown, ThrowOnError>({
    url: "/api/lots",
    ...options,
  });

export const getLotById = <ThrowOnError extends boolean = false>(
  options: Options<GetLotByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetLotByIdResponses,
    GetLotByIdErrors,
    ThrowOnError
  >({ url: "/api/lots/{id}", ...options });

export const getSales = <ThrowOnError extends boolean = false>(
  options: Options<GetSalesData, ThrowOnError>
) =>
  (options.client ?? client).get<GetSalesResponses, unknown, ThrowOnError>({
    url: "/api/sales",
    ...options,
  });

export const createSale = <ThrowOnError extends boolean = false>(
  options: Options<CreateSaleData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateSaleResponses,
    CreateSaleErrors,
    ThrowOnError
  >({
    url: "/api/sales",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const cancelSale = <ThrowOnError extends boolean = false>(
  options: Options<CancelSaleData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    CancelSaleResponses,
    CancelSaleErrors,
    ThrowOnError
  >({ url: "/api/sales/{id}", ...options });

export const getSaleById = <ThrowOnError extends boolean = false>(
  options: Options<GetSaleByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetSaleByIdResponses,
    GetSaleByIdErrors,
    ThrowOnError
  >({ url: "/api/sales/{id}", ...options });

export const getSaleDetailsBySale = <ThrowOnError extends boolean = false>(
  options: Options<GetSaleDetailsBySaleData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetSaleDetailsBySaleResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/sales/{id}/details", ...options });
