// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://127.0.0.1:5062/" | (string & {});
};

export type AccessTokenResponse = {
  tokenType?: null | string;
  accessToken: string;
  expiresIn: number | string;
  refreshToken: string;
};

export type CategoryBasicDto = {
  id: number | string;
  name: string;
  description?: null | string;
};

export type CategoryCreateDto = {
  name: string;
  description?: null | string;
};

export type FinancialSummaryDto = {
  totalRevenue: number | string;
  totalCostOfGoodsSold: number | string;
  grossProfit: number | string;
};

export type ForgotPasswordRequest = {
  email: string;
};

export type HttpValidationProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: null | number | string;
  detail?: null | string;
  instance?: null | string;
  errors?: {
    [key: string]: Array<string>;
  };
};

export type InfoRequest = {
  newEmail?: null | string;
  newPassword?: null | string;
  oldPassword?: null | string;
};

export type InfoResponse = {
  email: string;
  isEmailConfirmed: boolean;
};

export type LoginRequest = {
  email: string;
  password: string;
  twoFactorCode?: null | string;
  twoFactorRecoveryCode?: null | string;
};

export type LookupDto = {
  id: number | string;
  name: string;
};

export type LotBasicDto = {
  id: number | string;
  lotCode: string;
  entryDate: string;
  unitCost: number | string;
  availableQuantity: number | string;
  productId: number | string;
  purchaseId: number | string;
  product: ProductBasicDto;
};

export type LotExtended = {
  purchase: PurchaseBasicDto;
  id: number | string;
  lotCode: string;
  entryDate: string;
  unitCost: number | string;
  availableQuantity: number | string;
  productId: number | string;
  purchaseId: number | string;
  product: ProductBasicDto;
};

export type PagedListOfCategoryBasicDto = {
  items: Array<CategoryBasicDto>;
  totalCount: number | string;
  pageNumber: number | string;
  pageSize: number | string;
  totalPages?: number | string;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
};

export type PagedListOfLotBasicDto = {
  items: Array<LotBasicDto>;
  totalCount: number | string;
  pageNumber: number | string;
  pageSize: number | string;
  totalPages?: number | string;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
};

export type PagedListOfProductBasicDto = {
  items: Array<ProductBasicDto>;
  totalCount: number | string;
  pageNumber: number | string;
  pageSize: number | string;
  totalPages?: number | string;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
};

export type PagedListOfProductExtendedDto = {
  items: Array<ProductExtendedDto>;
  totalCount: number | string;
  pageNumber: number | string;
  pageSize: number | string;
  totalPages?: number | string;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
};

export type PagedListOfPurchaseBasicDto = {
  items: Array<PurchaseBasicDto>;
  totalCount: number | string;
  pageNumber: number | string;
  pageSize: number | string;
  totalPages?: number | string;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
};

export type PagedListOfSaleBasicDto = {
  items: Array<SaleBasicDto>;
  totalCount: number | string;
  pageNumber: number | string;
  pageSize: number | string;
  totalPages?: number | string;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
};

export type PagedListOfSaleDetailsBasicDto = {
  items: Array<SaleDetailsBasicDto>;
  totalCount: number | string;
  pageNumber: number | string;
  pageSize: number | string;
  totalPages?: number | string;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
};

export type PagedListOfSupplierBasicDto = {
  items: Array<SupplierBasicDto>;
  totalCount: number | string;
  pageNumber: number | string;
  pageSize: number | string;
  totalPages?: number | string;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
};

export type PagedListOfUnityOfMeasureBasicDto = {
  items: Array<UnityOfMeasureBasicDto>;
  totalCount: number | string;
  pageNumber: number | string;
  pageSize: number | string;
  totalPages?: number | string;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
};

export type ProductBasicDto = {
  id?: number | string;
  name: string;
  sku: string;
  description?: null | string;
  basePrice: number | string;
  categoryId: number | string;
  unityOfMeasureId: number | string;
};

export type ProductCreateDto = {
  name: string;
  sku: string;
  description?: null | string;
  basePrice: number | string;
  categoryId: number | string;
  unityOfMeasureId: number | string;
};

export type ProductExtendedDto = {
  id?: number | string;
  category: CategoryBasicDto;
  unityOfMeasure: UnityOfMeasureBasicDto;
  name: string;
  sku: string;
  description?: null | string;
  basePrice: number | string;
  categoryId: number | string;
  unityOfMeasureId: number | string;
};

export type PurchaseBasicDto = {
  id: number | string;
  referenceInvoice: string;
  totalCost: number | string;
  operationDate: string;
  status: Status;
  supplierId: number | string;
  userId: number | string;
};

export type PurchaseCreateDto = {
  referenceInvoice: string;
  operationDate: string;
  supplierId: number | string;
  purchaseItems: Array<PurchaseItemCreateDto>;
};

export type PurchaseExtendedDto = {
  supplier: SupplierBasicDto;
  user: UserBasicDto;
  id: number | string;
  referenceInvoice: string;
  totalCost: number | string;
  operationDate: string;
  status: Status;
  supplierId: number | string;
  userId: number | string;
};

export type PurchaseItemCreateDto = {
  productId: number | string;
  quantity: number | string;
  unitCost: number | string;
};

export type RecentTransactionDto = {
  transactionId: number | string;
  type: TransactionType;
  reference: string;
  operationDate: string;
  totalAmount: number | string;
};

export type RefreshRequest = {
  refreshToken: string;
};

export type RegisterRequest = {
  email: string;
  password: string;
};

export type ResendConfirmationEmailRequest = {
  email: string;
};

export type ResetPasswordRequest = {
  email: string;
  resetCode: string;
  newPassword: string;
};

export type SaleBasicDto = {
  id: number | string;
  referenceInvoice: string;
  totalRevenue: number | string;
  operationDate: string;
  status: Status;
  userId: number | string;
  user: UserBasicDto;
};

export type SaleCreateDto = {
  operationDate?: string;
  items: Array<SaleItemCreateDto>;
};

export type SaleDetailsBasicDto = {
  id?: number | string;
  quantityRequested: number | string;
  unitSellingPrice: number | string;
  productId: number | string;
  product: ProductBasicDto;
  subtotal?: number | string;
};

export type SaleItemCreateDto = {
  productId: number | string;
  quantity: number | string;
  unitPrice: number | string;
};

export type Status = number;

export type SupplierBasicDto = {
  id: number | string;
  name: string;
  taxId: string;
  contactInfo?: null | string;
};

export type SupplierCreateDto = {
  name: string;
  taxId: string;
  contactInfo?: null | string;
};

export type TransactionType = number;

export type TwoFactorRequest = {
  enable?: null | boolean;
  twoFactorCode?: null | string;
  resetSharedKey?: boolean;
  resetRecoveryCodes?: boolean;
  forgetMachine?: boolean;
};

export type TwoFactorResponse = {
  sharedKey: string;
  recoveryCodesLeft: number | string;
  recoveryCodes?: null | Array<string>;
  isTwoFactorEnabled: boolean;
  isMachineRemembered: boolean;
};

export type UnityOfMeasureBasicDto = {
  id: number | string;
  name: string;
  abbreviation: string;
};

export type UnityOfMeasureCreateDto = {
  name: string;
  abbreviation: string;
};

export type UserBasicDto = {
  id: number | string;
  email: null | string;
  fullName: string;
};

export type UserDto = {
  id: number | string;
  email: null | string;
  fullName: string;
  roles: Array<string>;
};

export type PostApiAuthRegisterData = {
  body: RegisterRequest;
  path?: never;
  query?: never;
  url: "/api/auth/register";
};

export type PostApiAuthRegisterErrors = {
  /**
   * Bad Request
   */
  400: HttpValidationProblemDetails;
};

export type PostApiAuthRegisterError =
  PostApiAuthRegisterErrors[keyof PostApiAuthRegisterErrors];

export type PostApiAuthRegisterResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiAuthLoginData = {
  body: LoginRequest;
  path?: never;
  query?: {
    useCookies?: boolean;
    useSessionCookies?: boolean;
  };
  url: "/api/auth/login";
};

export type PostApiAuthLoginResponses = {
  /**
   * OK
   */
  200: AccessTokenResponse;
};

export type PostApiAuthLoginResponse =
  PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthRefreshData = {
  body: RefreshRequest;
  path?: never;
  query?: never;
  url: "/api/auth/refresh";
};

export type PostApiAuthRefreshResponses = {
  /**
   * OK
   */
  200: AccessTokenResponse;
};

export type PostApiAuthRefreshResponse =
  PostApiAuthRefreshResponses[keyof PostApiAuthRefreshResponses];

export type MapIdentityApiApiAuthConfirmEmailData = {
  body?: never;
  path?: never;
  query: {
    userId: string;
    code: string;
    changedEmail?: string;
  };
  url: "/api/auth/confirmEmail";
};

export type MapIdentityApiApiAuthConfirmEmailResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiAuthResendConfirmationEmailData = {
  body: ResendConfirmationEmailRequest;
  path?: never;
  query?: never;
  url: "/api/auth/resendConfirmationEmail";
};

export type PostApiAuthResendConfirmationEmailResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiAuthForgotPasswordData = {
  body: ForgotPasswordRequest;
  path?: never;
  query?: never;
  url: "/api/auth/forgotPassword";
};

export type PostApiAuthForgotPasswordErrors = {
  /**
   * Bad Request
   */
  400: HttpValidationProblemDetails;
};

export type PostApiAuthForgotPasswordError =
  PostApiAuthForgotPasswordErrors[keyof PostApiAuthForgotPasswordErrors];

export type PostApiAuthForgotPasswordResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiAuthResetPasswordData = {
  body: ResetPasswordRequest;
  path?: never;
  query?: never;
  url: "/api/auth/resetPassword";
};

export type PostApiAuthResetPasswordErrors = {
  /**
   * Bad Request
   */
  400: HttpValidationProblemDetails;
};

export type PostApiAuthResetPasswordError =
  PostApiAuthResetPasswordErrors[keyof PostApiAuthResetPasswordErrors];

export type PostApiAuthResetPasswordResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiAuthManage2FaData = {
  body: TwoFactorRequest;
  path?: never;
  query?: never;
  url: "/api/auth/manage/2fa";
};

export type PostApiAuthManage2FaErrors = {
  /**
   * Bad Request
   */
  400: HttpValidationProblemDetails;
  /**
   * Not Found
   */
  404: unknown;
};

export type PostApiAuthManage2FaError =
  PostApiAuthManage2FaErrors[keyof PostApiAuthManage2FaErrors];

export type PostApiAuthManage2FaResponses = {
  /**
   * OK
   */
  200: TwoFactorResponse;
};

export type PostApiAuthManage2FaResponse =
  PostApiAuthManage2FaResponses[keyof PostApiAuthManage2FaResponses];

export type GetApiAuthManageInfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/manage/info";
};

export type GetApiAuthManageInfoErrors = {
  /**
   * Bad Request
   */
  400: HttpValidationProblemDetails;
  /**
   * Not Found
   */
  404: unknown;
};

export type GetApiAuthManageInfoError =
  GetApiAuthManageInfoErrors[keyof GetApiAuthManageInfoErrors];

export type GetApiAuthManageInfoResponses = {
  /**
   * OK
   */
  200: InfoResponse;
};

export type GetApiAuthManageInfoResponse =
  GetApiAuthManageInfoResponses[keyof GetApiAuthManageInfoResponses];

export type PostApiAuthManageInfoData = {
  body: InfoRequest;
  path?: never;
  query?: never;
  url: "/api/auth/manage/info";
};

export type PostApiAuthManageInfoErrors = {
  /**
   * Bad Request
   */
  400: HttpValidationProblemDetails;
  /**
   * Not Found
   */
  404: unknown;
};

export type PostApiAuthManageInfoError =
  PostApiAuthManageInfoErrors[keyof PostApiAuthManageInfoErrors];

export type PostApiAuthManageInfoResponses = {
  /**
   * OK
   */
  200: InfoResponse;
};

export type PostApiAuthManageInfoResponse =
  PostApiAuthManageInfoResponses[keyof PostApiAuthManageInfoResponses];

export type GetUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/me";
};

export type GetUserErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type GetUserResponses = {
  /**
   * OK
   */
  200: UserDto;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type GetProductsData = {
  body?: never;
  path?: never;
  query: {
    PageNumber: number | string;
    PageSize: number | string;
    SearchTerm?: string;
  };
  url: "/api/products";
};

export type GetProductsResponses = {
  /**
   * OK
   */
  200: PagedListOfProductExtendedDto;
};

export type GetProductsResponse =
  GetProductsResponses[keyof GetProductsResponses];

export type CreateProductData = {
  body: ProductCreateDto;
  path?: never;
  query?: never;
  url: "/api/products";
};

export type CreateProductErrors = {
  /**
   * Bad Request
   */
  400: string;
};

export type CreateProductError = CreateProductErrors[keyof CreateProductErrors];

export type CreateProductResponses = {
  /**
   * Created
   */
  201: ProductBasicDto;
};

export type CreateProductResponse =
  CreateProductResponses[keyof CreateProductResponses];

export type DeleteProductData = {
  body?: never;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/products/{id}";
};

export type DeleteProductErrors = {
  /**
   * Bad Request
   */
  400: string;
};

export type DeleteProductError = DeleteProductErrors[keyof DeleteProductErrors];

export type DeleteProductResponses = {
  /**
   * OK
   */
  200: number | string;
};

export type DeleteProductResponse =
  DeleteProductResponses[keyof DeleteProductResponses];

export type GetProductByIdData = {
  body?: never;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/products/{id}";
};

export type GetProductByIdErrors = {
  /**
   * Not Found
   */
  404: string;
};

export type GetProductByIdError =
  GetProductByIdErrors[keyof GetProductByIdErrors];

export type GetProductByIdResponses = {
  /**
   * OK
   */
  200: ProductExtendedDto;
};

export type GetProductByIdResponse =
  GetProductByIdResponses[keyof GetProductByIdResponses];

export type UpdateProductData = {
  body: ProductBasicDto;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/products/{id}";
};

export type UpdateProductErrors = {
  /**
   * Bad Request
   */
  400: string;
};

export type UpdateProductError = UpdateProductErrors[keyof UpdateProductErrors];

export type UpdateProductResponses = {
  /**
   * OK
   */
  200: ProductBasicDto;
};

export type UpdateProductResponse =
  UpdateProductResponses[keyof UpdateProductResponses];

export type GetLotsByProductData = {
  body?: never;
  path: {
    id: number | string;
  };
  query: {
    PageNumber: number | string;
    PageSize: number | string;
    SearchTerm?: string;
  };
  url: "/api/products/{id}/lots";
};

export type GetLotsByProductResponses = {
  /**
   * OK
   */
  200: PagedListOfLotBasicDto;
};

export type GetLotsByProductResponse =
  GetLotsByProductResponses[keyof GetLotsByProductResponses];

export type GetProductsLookupData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/products/lookup";
};

export type GetProductsLookupResponses = {
  /**
   * OK
   */
  200: Array<LookupDto>;
};

export type GetProductsLookupResponse =
  GetProductsLookupResponses[keyof GetProductsLookupResponses];

export type GetCategoriesData = {
  body?: never;
  path?: never;
  query: {
    PageNumber: number | string;
    PageSize: number | string;
    SearchTerm?: string;
  };
  url: "/api/categories";
};

export type GetCategoriesResponses = {
  /**
   * OK
   */
  200: PagedListOfCategoryBasicDto;
};

export type GetCategoriesResponse =
  GetCategoriesResponses[keyof GetCategoriesResponses];

export type CreateCategoryData = {
  body: CategoryCreateDto;
  path?: never;
  query?: never;
  url: "/api/categories";
};

export type CreateCategoryErrors = {
  /**
   * Bad Request
   */
  400: string;
};

export type CreateCategoryError =
  CreateCategoryErrors[keyof CreateCategoryErrors];

export type CreateCategoryResponses = {
  /**
   * Created
   */
  201: CategoryBasicDto;
};

export type CreateCategoryResponse =
  CreateCategoryResponses[keyof CreateCategoryResponses];

export type DeleteCategoryData = {
  body?: never;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/categories/{id}";
};

export type DeleteCategoryErrors = {
  /**
   * Bad Request
   */
  400: string;
};

export type DeleteCategoryError =
  DeleteCategoryErrors[keyof DeleteCategoryErrors];

export type DeleteCategoryResponses = {
  /**
   * OK
   */
  200: number | string;
};

export type DeleteCategoryResponse =
  DeleteCategoryResponses[keyof DeleteCategoryResponses];

export type GetCategoryByIdData = {
  body?: never;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/categories/{id}";
};

export type GetCategoryByIdErrors = {
  /**
   * Not Found
   */
  404: string;
};

export type GetCategoryByIdError =
  GetCategoryByIdErrors[keyof GetCategoryByIdErrors];

export type GetCategoryByIdResponses = {
  /**
   * OK
   */
  200: CategoryBasicDto;
};

export type GetCategoryByIdResponse =
  GetCategoryByIdResponses[keyof GetCategoryByIdResponses];

export type UpdateCategoryData = {
  body: CategoryBasicDto;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/categories/{id}";
};

export type UpdateCategoryErrors = {
  /**
   * Bad Request
   */
  400: string;
};

export type UpdateCategoryError =
  UpdateCategoryErrors[keyof UpdateCategoryErrors];

export type UpdateCategoryResponses = {
  /**
   * OK
   */
  200: CategoryBasicDto;
};

export type UpdateCategoryResponse =
  UpdateCategoryResponses[keyof UpdateCategoryResponses];

export type GetProductsByCategoryData = {
  body?: never;
  path: {
    id: number | string;
  };
  query: {
    PageNumber: number | string;
    PageSize: number | string;
    SearchTerm?: string;
  };
  url: "/api/categories/{id}/products";
};

export type GetProductsByCategoryResponses = {
  /**
   * OK
   */
  200: PagedListOfProductBasicDto;
};

export type GetProductsByCategoryResponse =
  GetProductsByCategoryResponses[keyof GetProductsByCategoryResponses];

export type GetCategoriesLookupData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/categories/lookup";
};

export type GetCategoriesLookupResponses = {
  /**
   * OK
   */
  200: Array<LookupDto>;
};

export type GetCategoriesLookupResponse =
  GetCategoriesLookupResponses[keyof GetCategoriesLookupResponses];

export type GetSuppliersData = {
  body?: never;
  path?: never;
  query: {
    PageNumber: number | string;
    PageSize: number | string;
    SearchTerm?: string;
  };
  url: "/api/suppliers";
};

export type GetSuppliersResponses = {
  /**
   * OK
   */
  200: PagedListOfSupplierBasicDto;
};

export type GetSuppliersResponse =
  GetSuppliersResponses[keyof GetSuppliersResponses];

export type CreateSupplierData = {
  body: SupplierCreateDto;
  path?: never;
  query?: never;
  url: "/api/suppliers";
};

export type CreateSupplierErrors = {
  /**
   * Bad Request
   */
  400: string;
};

export type CreateSupplierError =
  CreateSupplierErrors[keyof CreateSupplierErrors];

export type CreateSupplierResponses = {
  /**
   * Created
   */
  201: SupplierBasicDto;
};

export type CreateSupplierResponse =
  CreateSupplierResponses[keyof CreateSupplierResponses];

export type DeleteSupplierData = {
  body?: never;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/suppliers/{id}";
};

export type DeleteSupplierErrors = {
  /**
   * Bad Request
   */
  400: string;
};

export type DeleteSupplierError =
  DeleteSupplierErrors[keyof DeleteSupplierErrors];

export type DeleteSupplierResponses = {
  /**
   * OK
   */
  200: number | string;
};

export type DeleteSupplierResponse =
  DeleteSupplierResponses[keyof DeleteSupplierResponses];

export type GetSupplierByIdData = {
  body?: never;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/suppliers/{id}";
};

export type GetSupplierByIdErrors = {
  /**
   * Not Found
   */
  404: string;
};

export type GetSupplierByIdError =
  GetSupplierByIdErrors[keyof GetSupplierByIdErrors];

export type GetSupplierByIdResponses = {
  /**
   * OK
   */
  200: SupplierBasicDto;
};

export type GetSupplierByIdResponse =
  GetSupplierByIdResponses[keyof GetSupplierByIdResponses];

export type UpdateSupplierData = {
  body: SupplierBasicDto;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/suppliers/{id}";
};

export type UpdateSupplierErrors = {
  /**
   * Bad Request
   */
  400: string;
};

export type UpdateSupplierError =
  UpdateSupplierErrors[keyof UpdateSupplierErrors];

export type UpdateSupplierResponses = {
  /**
   * OK
   */
  200: SupplierBasicDto;
};

export type UpdateSupplierResponse =
  UpdateSupplierResponses[keyof UpdateSupplierResponses];

export type GetPurchasesBySupplierData = {
  body?: never;
  path: {
    id: number | string;
  };
  query: {
    PageNumber: number | string;
    PageSize: number | string;
    SearchTerm?: string;
  };
  url: "/api/suppliers/{id}/purchases";
};

export type GetPurchasesBySupplierResponses = {
  /**
   * OK
   */
  200: PagedListOfPurchaseBasicDto;
};

export type GetPurchasesBySupplierResponse =
  GetPurchasesBySupplierResponses[keyof GetPurchasesBySupplierResponses];

export type GetSuppliersLookupData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/suppliers/lookup";
};

export type GetSuppliersLookupResponses = {
  /**
   * OK
   */
  200: Array<LookupDto>;
};

export type GetSuppliersLookupResponse =
  GetSuppliersLookupResponses[keyof GetSuppliersLookupResponses];

export type GetUnitsOfMeasureData = {
  body?: never;
  path?: never;
  query: {
    PageNumber: number | string;
    PageSize: number | string;
    SearchTerm?: string;
  };
  url: "/api/units-of-measure";
};

export type GetUnitsOfMeasureResponses = {
  /**
   * OK
   */
  200: PagedListOfUnityOfMeasureBasicDto;
};

export type GetUnitsOfMeasureResponse =
  GetUnitsOfMeasureResponses[keyof GetUnitsOfMeasureResponses];

export type CreateUnityOfMeasureData = {
  body: UnityOfMeasureCreateDto;
  path?: never;
  query?: never;
  url: "/api/units-of-measure";
};

export type CreateUnityOfMeasureErrors = {
  /**
   * Bad Request
   */
  400: string;
};

export type CreateUnityOfMeasureError =
  CreateUnityOfMeasureErrors[keyof CreateUnityOfMeasureErrors];

export type CreateUnityOfMeasureResponses = {
  /**
   * Created
   */
  201: UnityOfMeasureBasicDto;
};

export type CreateUnityOfMeasureResponse =
  CreateUnityOfMeasureResponses[keyof CreateUnityOfMeasureResponses];

export type DeleteUnityOfMeasureData = {
  body?: never;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/units-of-measure/{id}";
};

export type DeleteUnityOfMeasureErrors = {
  /**
   * Bad Request
   */
  400: string;
};

export type DeleteUnityOfMeasureError =
  DeleteUnityOfMeasureErrors[keyof DeleteUnityOfMeasureErrors];

export type DeleteUnityOfMeasureResponses = {
  /**
   * OK
   */
  200: number | string;
};

export type DeleteUnityOfMeasureResponse =
  DeleteUnityOfMeasureResponses[keyof DeleteUnityOfMeasureResponses];

export type GetUnityOfMeasureByIdData = {
  body?: never;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/units-of-measure/{id}";
};

export type GetUnityOfMeasureByIdErrors = {
  /**
   * Not Found
   */
  404: string;
};

export type GetUnityOfMeasureByIdError =
  GetUnityOfMeasureByIdErrors[keyof GetUnityOfMeasureByIdErrors];

export type GetUnityOfMeasureByIdResponses = {
  /**
   * OK
   */
  200: UnityOfMeasureBasicDto;
};

export type GetUnityOfMeasureByIdResponse =
  GetUnityOfMeasureByIdResponses[keyof GetUnityOfMeasureByIdResponses];

export type UpdateUnityOfMeasureData = {
  body: UnityOfMeasureBasicDto;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/units-of-measure/{id}";
};

export type UpdateUnityOfMeasureErrors = {
  /**
   * Bad Request
   */
  400: string;
};

export type UpdateUnityOfMeasureError =
  UpdateUnityOfMeasureErrors[keyof UpdateUnityOfMeasureErrors];

export type UpdateUnityOfMeasureResponses = {
  /**
   * OK
   */
  200: UnityOfMeasureBasicDto;
};

export type UpdateUnityOfMeasureResponse =
  UpdateUnityOfMeasureResponses[keyof UpdateUnityOfMeasureResponses];

export type GetProductsByUnityOfMeasureData = {
  body?: never;
  path: {
    id: number | string;
  };
  query: {
    PageNumber: number | string;
    PageSize: number | string;
    SearchTerm?: string;
  };
  url: "/api/units-of-measure/{id}/products";
};

export type GetProductsByUnityOfMeasureResponses = {
  /**
   * OK
   */
  200: PagedListOfProductBasicDto;
};

export type GetProductsByUnityOfMeasureResponse =
  GetProductsByUnityOfMeasureResponses[keyof GetProductsByUnityOfMeasureResponses];

export type GetUnitsOfMeasureLookupData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/units-of-measure/lookup";
};

export type GetUnitsOfMeasureLookupResponses = {
  /**
   * OK
   */
  200: Array<LookupDto>;
};

export type GetUnitsOfMeasureLookupResponse =
  GetUnitsOfMeasureLookupResponses[keyof GetUnitsOfMeasureLookupResponses];

export type GetPurchasesData = {
  body?: never;
  path?: never;
  query: {
    PageNumber: number | string;
    PageSize: number | string;
    SearchTerm?: string;
  };
  url: "/api/purchases";
};

export type GetPurchasesResponses = {
  /**
   * OK
   */
  200: PagedListOfPurchaseBasicDto;
};

export type GetPurchasesResponse =
  GetPurchasesResponses[keyof GetPurchasesResponses];

export type CreatePurchaseData = {
  body: PurchaseCreateDto;
  path?: never;
  query?: never;
  url: "/api/purchases";
};

export type CreatePurchaseErrors = {
  /**
   * Bad Request
   */
  400: string;
};

export type CreatePurchaseError =
  CreatePurchaseErrors[keyof CreatePurchaseErrors];

export type CreatePurchaseResponses = {
  /**
   * Created
   */
  201: PurchaseBasicDto;
};

export type CreatePurchaseResponse =
  CreatePurchaseResponses[keyof CreatePurchaseResponses];

export type CancelPurchaseData = {
  body?: never;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/purchases/{id}";
};

export type CancelPurchaseErrors = {
  /**
   * Bad Request
   */
  400: string;
};

export type CancelPurchaseError =
  CancelPurchaseErrors[keyof CancelPurchaseErrors];

export type CancelPurchaseResponses = {
  /**
   * OK
   */
  200: number | string;
};

export type CancelPurchaseResponse =
  CancelPurchaseResponses[keyof CancelPurchaseResponses];

export type GetPurchaseByIdData = {
  body?: never;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/purchases/{id}";
};

export type GetPurchaseByIdErrors = {
  /**
   * Not Found
   */
  404: string;
};

export type GetPurchaseByIdError =
  GetPurchaseByIdErrors[keyof GetPurchaseByIdErrors];

export type GetPurchaseByIdResponses = {
  /**
   * OK
   */
  200: PurchaseExtendedDto;
};

export type GetPurchaseByIdResponse =
  GetPurchaseByIdResponses[keyof GetPurchaseByIdResponses];

export type GetLotsByPurchaseData = {
  body?: never;
  path: {
    id: number | string;
  };
  query: {
    PageNumber: number | string;
    PageSize: number | string;
    SearchTerm?: string;
  };
  url: "/api/purchases/{id}/lots";
};

export type GetLotsByPurchaseResponses = {
  /**
   * OK
   */
  200: PagedListOfLotBasicDto;
};

export type GetLotsByPurchaseResponse =
  GetLotsByPurchaseResponses[keyof GetLotsByPurchaseResponses];

export type GetLotsData = {
  body?: never;
  path?: never;
  query: {
    PageNumber: number | string;
    PageSize: number | string;
    SearchTerm?: string;
  };
  url: "/api/lots";
};

export type GetLotsResponses = {
  /**
   * OK
   */
  200: PagedListOfLotBasicDto;
};

export type GetLotsResponse = GetLotsResponses[keyof GetLotsResponses];

export type GetLotByIdData = {
  body?: never;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/lots/{id}";
};

export type GetLotByIdErrors = {
  /**
   * Not Found
   */
  404: string;
};

export type GetLotByIdError = GetLotByIdErrors[keyof GetLotByIdErrors];

export type GetLotByIdResponses = {
  /**
   * OK
   */
  200: LotExtended;
};

export type GetLotByIdResponse = GetLotByIdResponses[keyof GetLotByIdResponses];

export type GetSalesData = {
  body?: never;
  path?: never;
  query: {
    PageNumber: number | string;
    PageSize: number | string;
    SearchTerm?: string;
  };
  url: "/api/sales";
};

export type GetSalesResponses = {
  /**
   * OK
   */
  200: PagedListOfSaleBasicDto;
};

export type GetSalesResponse = GetSalesResponses[keyof GetSalesResponses];

export type CreateSaleData = {
  body: SaleCreateDto;
  path?: never;
  query?: never;
  url: "/api/sales";
};

export type CreateSaleErrors = {
  /**
   * Bad Request
   */
  400: string;
};

export type CreateSaleError = CreateSaleErrors[keyof CreateSaleErrors];

export type CreateSaleResponses = {
  /**
   * Created
   */
  201: SaleBasicDto;
};

export type CreateSaleResponse = CreateSaleResponses[keyof CreateSaleResponses];

export type CancelSaleData = {
  body?: never;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/sales/{id}";
};

export type CancelSaleErrors = {
  /**
   * Bad Request
   */
  400: string;
  /**
   * Not Found
   */
  404: string;
};

export type CancelSaleError = CancelSaleErrors[keyof CancelSaleErrors];

export type CancelSaleResponses = {
  /**
   * OK
   */
  200: number | string;
};

export type CancelSaleResponse = CancelSaleResponses[keyof CancelSaleResponses];

export type GetSaleByIdData = {
  body?: never;
  path: {
    id: number | string;
  };
  query?: never;
  url: "/api/sales/{id}";
};

export type GetSaleByIdErrors = {
  /**
   * Not Found
   */
  404: string;
};

export type GetSaleByIdError = GetSaleByIdErrors[keyof GetSaleByIdErrors];

export type GetSaleByIdResponses = {
  /**
   * OK
   */
  200: SaleBasicDto;
};

export type GetSaleByIdResponse =
  GetSaleByIdResponses[keyof GetSaleByIdResponses];

export type GetSaleDetailsBySaleData = {
  body?: never;
  path: {
    id: number | string;
  };
  query: {
    PageNumber: number | string;
    PageSize: number | string;
    SearchTerm?: string;
  };
  url: "/api/sales/{id}/details";
};

export type GetSaleDetailsBySaleResponses = {
  /**
   * OK
   */
  200: PagedListOfSaleDetailsBasicDto;
};

export type GetSaleDetailsBySaleResponse =
  GetSaleDetailsBySaleResponses[keyof GetSaleDetailsBySaleResponses];

export type GetFinancialSummaryData = {
  body?: never;
  path?: never;
  query: {
    StartDate: string;
    EndDate: string;
  };
  url: "/api/dashboard/summary";
};

export type GetFinancialSummaryResponses = {
  /**
   * OK
   */
  200: FinancialSummaryDto;
};

export type GetFinancialSummaryResponse =
  GetFinancialSummaryResponses[keyof GetFinancialSummaryResponses];

export type GetRecentTransactionsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number | string;
  };
  url: "/api/dashboard/recent-transactions";
};

export type GetRecentTransactionsResponses = {
  /**
   * OK
   */
  200: Array<RecentTransactionDto>;
};

export type GetRecentTransactionsResponse =
  GetRecentTransactionsResponses[keyof GetRecentTransactionsResponses];
