// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const zAccessTokenResponse = z.object({
  tokenType: z.string().nullish(),
  accessToken: z.string(),
  expiresIn: z.union([
    z.coerce
      .bigint()
      .min(BigInt("-9223372036854775808"), {
        error: "Invalid value: Expected int64 to be >= -9223372036854775808",
      })
      .max(BigInt("9223372036854775807"), {
        error: "Invalid value: Expected int64 to be <= 9223372036854775807",
      }),
    z.coerce
      .bigint()
      .min(BigInt("-9223372036854775808"), {
        error: "Invalid value: Expected int64 to be >= -9223372036854775808",
      })
      .max(BigInt("9223372036854775807"), {
        error: "Invalid value: Expected int64 to be <= 9223372036854775807",
      }),
  ]),
  refreshToken: z.string(),
});

export const zCategoryBasicDto = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  name: z.string().min(1).max(50),
  description: z.string().max(200).nullish(),
});

export const zCategoryCreateDto = z.object({
  name: z.string().min(1).max(50),
  description: z.string().max(200).nullish(),
});

export const zForgotPasswordRequest = z.object({
  email: z.string(),
});

export const zHttpValidationProblemDetails = z.object({
  type: z.string().nullish(),
  title: z.string().nullish(),
  status: z
    .union([
      z
        .int()
        .min(-2147483648, {
          error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
          error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ])
    .nullish(),
  detail: z.string().nullish(),
  instance: z.string().nullish(),
  errors: z.record(z.string(), z.array(z.string())).optional(),
});

export const zInfoRequest = z.object({
  newEmail: z.string().nullish(),
  newPassword: z.string().nullish(),
  oldPassword: z.string().nullish(),
});

export const zInfoResponse = z.object({
  email: z.string(),
  isEmailConfirmed: z.boolean(),
});

export const zLoginRequest = z.object({
  email: z.string(),
  password: z.string(),
  twoFactorCode: z.string().nullish(),
  twoFactorRecoveryCode: z.string().nullish(),
});

export const zLookupDto = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  name: z.string(),
});

export const zPagedListOfCategoryBasicDto = z.object({
  items: z.array(zCategoryBasicDto),
  totalCount: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  totalPages: z
    .union([
      z
        .int()
        .min(-2147483648, {
          error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
          error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ])
    .optional(),
  hasNextPage: z.boolean().optional(),
  hasPreviousPage: z.boolean().optional(),
});

export const zProductBasicDto = z.object({
  id: z
    .union([
      z
        .int()
        .min(-2147483648, {
          error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
          error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ])
    .optional(),
  name: z.string().min(1).max(50),
  sku: z.string().min(1).max(50),
  description: z.string().max(200).nullish(),
  basePrice: z.union([
    z.number().gte(0.01),
    z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/),
  ]),
  categoryId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  unityOfMeasureId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

export const zLotBasicDto = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  lotCode: z.string().min(1).max(100),
  entryDate: z.iso.datetime(),
  unitCost: z.union([
    z.number().gte(0.01),
    z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/),
  ]),
  availableQuantity: z.union([
    z.number().gte(0.0001),
    z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/),
  ]),
  productId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  purchaseId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  product: zProductBasicDto,
});

export const zPagedListOfLotBasicDto = z.object({
  items: z.array(zLotBasicDto),
  totalCount: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  totalPages: z
    .union([
      z
        .int()
        .min(-2147483648, {
          error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
          error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ])
    .optional(),
  hasNextPage: z.boolean().optional(),
  hasPreviousPage: z.boolean().optional(),
});

export const zPagedListOfProductBasicDto = z.object({
  items: z.array(zProductBasicDto),
  totalCount: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  totalPages: z
    .union([
      z
        .int()
        .min(-2147483648, {
          error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
          error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ])
    .optional(),
  hasNextPage: z.boolean().optional(),
  hasPreviousPage: z.boolean().optional(),
});

export const zProductCreateDto = z.object({
  name: z.string().min(1).max(50),
  sku: z.string().min(1).max(50),
  description: z.string().max(200).nullish(),
  basePrice: z.union([
    z.number().gte(0.01),
    z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/),
  ]),
  categoryId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  unityOfMeasureId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

export const zPurchaseItemCreateDto = z.object({
  productId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  quantity: z.union([
    z.number().gte(0.0001),
    z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/),
  ]),
  unitCost: z.union([
    z.number().gte(0),
    z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/),
  ]),
});

export const zPurchaseCreateDto = z.object({
  referenceInvoice: z.string().min(1).max(50),
  operationDate: z.iso.datetime(),
  supplierId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  purchaseItems: z.array(zPurchaseItemCreateDto),
});

export const zRefreshRequest = z.object({
  refreshToken: z.string(),
});

export const zRegisterRequest = z.object({
  email: z.string(),
  password: z.string(),
});

export const zResendConfirmationEmailRequest = z.object({
  email: z.string(),
});

export const zResetPasswordRequest = z.object({
  email: z.string(),
  resetCode: z.string(),
  newPassword: z.string(),
});

export const zSaleDetailsBasicDto = z.object({
  id: z
    .union([
      z
        .int()
        .min(-2147483648, {
          error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
          error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ])
    .optional(),
  quantityRequested: z.union([
    z.number().gte(0.0001),
    z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/),
  ]),
  unitSellingPrice: z.union([
    z.number().gte(0.01),
    z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/),
  ]),
  productId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  product: zProductBasicDto,
  subtotal: z
    .union([z.number(), z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/)])
    .optional(),
});

export const zPagedListOfSaleDetailsBasicDto = z.object({
  items: z.array(zSaleDetailsBasicDto),
  totalCount: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  totalPages: z
    .union([
      z
        .int()
        .min(-2147483648, {
          error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
          error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ])
    .optional(),
  hasNextPage: z.boolean().optional(),
  hasPreviousPage: z.boolean().optional(),
});

export const zSaleItemCreateDto = z.object({
  productId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  quantity: z.union([
    z.number().gte(0.0001),
    z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/),
  ]),
  unitPrice: z.union([
    z.number().gte(0.01),
    z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/),
  ]),
});

export const zSaleCreateDto = z.object({
  operationDate: z.iso.datetime().optional(),
  items: z.array(zSaleItemCreateDto).min(1),
});

export const zStatus = z.int();

export const zPurchaseBasicDto = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  referenceInvoice: z.string().min(1).max(50),
  totalAmount: z.union([
    z.number().gte(0.01),
    z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/),
  ]),
  operationDate: z.iso.datetime(),
  status: zStatus,
  supplierId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  userId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

export const zLotExtended = z.object({
  purchase: zPurchaseBasicDto,
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  lotCode: z.string().min(1).max(100),
  entryDate: z.iso.datetime(),
  unitCost: z.union([
    z.number().gte(0.01),
    z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/),
  ]),
  availableQuantity: z.union([
    z.number().gte(0.0001),
    z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/),
  ]),
  productId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  purchaseId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  product: zProductBasicDto,
});

export const zPagedListOfPurchaseBasicDto = z.object({
  items: z.array(zPurchaseBasicDto),
  totalCount: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  totalPages: z
    .union([
      z
        .int()
        .min(-2147483648, {
          error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
          error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ])
    .optional(),
  hasNextPage: z.boolean().optional(),
  hasPreviousPage: z.boolean().optional(),
});

export const zSupplierBasicDto = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  name: z.string().min(1).max(100),
  taxId: z.string().min(1).max(20),
  contactInfo: z.string().nullish(),
});

export const zPagedListOfSupplierBasicDto = z.object({
  items: z.array(zSupplierBasicDto),
  totalCount: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  totalPages: z
    .union([
      z
        .int()
        .min(-2147483648, {
          error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
          error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ])
    .optional(),
  hasNextPage: z.boolean().optional(),
  hasPreviousPage: z.boolean().optional(),
});

export const zSupplierCreateDto = z.object({
  name: z.string().min(1).max(100),
  taxId: z.string().min(1).max(20),
  contactInfo: z.string().nullish(),
});

export const zTwoFactorRequest = z.object({
  enable: z.boolean().nullish(),
  twoFactorCode: z.string().nullish(),
  resetSharedKey: z.boolean().optional(),
  resetRecoveryCodes: z.boolean().optional(),
  forgetMachine: z.boolean().optional(),
});

export const zTwoFactorResponse = z.object({
  sharedKey: z.string(),
  recoveryCodesLeft: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  recoveryCodes: z.array(z.string()).nullish(),
  isTwoFactorEnabled: z.boolean(),
  isMachineRemembered: z.boolean(),
});

export const zUnityOfMeasureBasicDto = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  name: z.string().min(1).max(50),
  abbreviation: z.string().min(1).max(10),
});

export const zPagedListOfUnityOfMeasureBasicDto = z.object({
  items: z.array(zUnityOfMeasureBasicDto),
  totalCount: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  totalPages: z
    .union([
      z
        .int()
        .min(-2147483648, {
          error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
          error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ])
    .optional(),
  hasNextPage: z.boolean().optional(),
  hasPreviousPage: z.boolean().optional(),
});

export const zProductExtendedDto = z.object({
  id: z
    .union([
      z
        .int()
        .min(-2147483648, {
          error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
          error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ])
    .optional(),
  category: zCategoryBasicDto,
  unityOfMeasure: zUnityOfMeasureBasicDto,
  name: z.string().min(1).max(50),
  sku: z.string().min(1).max(50),
  description: z.string().max(200).nullish(),
  basePrice: z.union([
    z.number().gte(0.01),
    z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/),
  ]),
  categoryId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  unityOfMeasureId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

export const zPagedListOfProductExtendedDto = z.object({
  items: z.array(zProductExtendedDto),
  totalCount: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  totalPages: z
    .union([
      z
        .int()
        .min(-2147483648, {
          error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
          error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ])
    .optional(),
  hasNextPage: z.boolean().optional(),
  hasPreviousPage: z.boolean().optional(),
});

export const zUnityOfMeasureCreateDto = z.object({
  name: z.string().min(1).max(50),
  abbreviation: z.string().min(1).max(10),
});

export const zUserBasicDto = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  email: z.string().nullable(),
  fullName: z.string(),
});

export const zPurchaseExtendedDto = z.object({
  supplier: zSupplierBasicDto,
  user: zUserBasicDto,
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  referenceInvoice: z.string().min(1).max(50),
  totalAmount: z.union([
    z.number().gte(0.01),
    z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/),
  ]),
  operationDate: z.iso.datetime(),
  status: zStatus,
  supplierId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  userId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

export const zSaleBasicDto = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  referenceInvoice: z.string().min(1).max(50),
  totalAmount: z.union([
    z.number().gte(0.01),
    z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/),
  ]),
  operationDate: z.iso.datetime(),
  status: zStatus,
  userId: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  user: zUserBasicDto,
});

export const zPagedListOfSaleBasicDto = z.object({
  items: z.array(zSaleBasicDto),
  totalCount: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  pageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  totalPages: z
    .union([
      z
        .int()
        .min(-2147483648, {
          error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
          error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ])
    .optional(),
  hasNextPage: z.boolean().optional(),
  hasPreviousPage: z.boolean().optional(),
});

export const zUserDto = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  email: z.string().nullable(),
  fullName: z.string(),
  roles: z.array(z.string()),
});

export const zPostApiAuthRegisterBody = zRegisterRequest;

export const zPostApiAuthLoginBody = zLoginRequest;

export const zPostApiAuthLoginQuery = z.object({
  useCookies: z.boolean().optional(),
  useSessionCookies: z.boolean().optional(),
});

/**
 * OK
 */
export const zPostApiAuthLoginResponse = zAccessTokenResponse;

export const zPostApiAuthRefreshBody = zRefreshRequest;

/**
 * OK
 */
export const zPostApiAuthRefreshResponse = zAccessTokenResponse;

export const zMapIdentityApiApiAuthConfirmEmailQuery = z.object({
  userId: z.string(),
  code: z.string(),
  changedEmail: z.string().optional(),
});

export const zPostApiAuthResendConfirmationEmailBody =
  zResendConfirmationEmailRequest;

export const zPostApiAuthForgotPasswordBody = zForgotPasswordRequest;

export const zPostApiAuthResetPasswordBody = zResetPasswordRequest;

export const zPostApiAuthManage2FaBody = zTwoFactorRequest;

/**
 * OK
 */
export const zPostApiAuthManage2FaResponse = zTwoFactorResponse;

/**
 * OK
 */
export const zGetApiAuthManageInfoResponse = zInfoResponse;

export const zPostApiAuthManageInfoBody = zInfoRequest;

/**
 * OK
 */
export const zPostApiAuthManageInfoResponse = zInfoResponse;

/**
 * OK
 */
export const zGetUserResponse = zUserDto;

export const zGetProductsQuery = z.object({
  PageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  PageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  SearchTerm: z.string().optional(),
});

/**
 * OK
 */
export const zGetProductsResponse = zPagedListOfProductExtendedDto;

export const zCreateProductBody = zProductCreateDto;

/**
 * Created
 */
export const zCreateProductResponse = zProductBasicDto;

export const zDeleteProductPath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zDeleteProductResponse = z.union([
  z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    }),
  z.string().regex(/^-?(?:0|[1-9]\d*)$/),
]);

export const zGetProductByIdPath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zGetProductByIdResponse = zProductExtendedDto;

export const zUpdateProductBody = zProductBasicDto;

export const zUpdateProductPath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zUpdateProductResponse = zProductBasicDto;

/**
 * OK
 */
export const zGetProductsLookupResponse = z.array(zLookupDto);

export const zGetCategoriesQuery = z.object({
  PageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  PageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  SearchTerm: z.string().optional(),
});

/**
 * OK
 */
export const zGetCategoriesResponse = zPagedListOfCategoryBasicDto;

export const zCreateCategoryBody = zCategoryCreateDto;

/**
 * Created
 */
export const zCreateCategoryResponse = zCategoryBasicDto;

export const zDeleteCategoryPath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zDeleteCategoryResponse = z.union([
  z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    }),
  z.string().regex(/^-?(?:0|[1-9]\d*)$/),
]);

export const zGetCategoryByIdPath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zGetCategoryByIdResponse = zCategoryBasicDto;

export const zUpdateCategoryBody = zCategoryBasicDto;

export const zUpdateCategoryPath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zUpdateCategoryResponse = zCategoryBasicDto;

export const zGetProductsByCategoryPath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

export const zGetProductsByCategoryQuery = z.object({
  PageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  PageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  SearchTerm: z.string().optional(),
});

/**
 * OK
 */
export const zGetProductsByCategoryResponse = zPagedListOfProductBasicDto;

/**
 * OK
 */
export const zGetCategoriesLookupResponse = z.array(zLookupDto);

export const zGetSuppliersQuery = z.object({
  PageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  PageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  SearchTerm: z.string().optional(),
});

/**
 * OK
 */
export const zGetSuppliersResponse = zPagedListOfSupplierBasicDto;

export const zCreateSupplierBody = zSupplierCreateDto;

/**
 * Created
 */
export const zCreateSupplierResponse = zSupplierBasicDto;

export const zDeleteSupplierPath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zDeleteSupplierResponse = z.union([
  z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    }),
  z.string().regex(/^-?(?:0|[1-9]\d*)$/),
]);

export const zGetSupplierByIdPath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zGetSupplierByIdResponse = zSupplierBasicDto;

export const zUpdateSupplierBody = zSupplierBasicDto;

export const zUpdateSupplierPath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zUpdateSupplierResponse = zSupplierBasicDto;

export const zGetPurchasesBySupplierPath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

export const zGetPurchasesBySupplierQuery = z.object({
  PageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  PageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  SearchTerm: z.string().optional(),
});

/**
 * OK
 */
export const zGetPurchasesBySupplierResponse = zPagedListOfPurchaseBasicDto;

/**
 * OK
 */
export const zGetSuppliersLookupResponse = z.array(zLookupDto);

export const zGetUnitsOfMeasureQuery = z.object({
  PageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  PageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  SearchTerm: z.string().optional(),
});

/**
 * OK
 */
export const zGetUnitsOfMeasureResponse = zPagedListOfUnityOfMeasureBasicDto;

export const zCreateUnityOfMeasureBody = zUnityOfMeasureCreateDto;

/**
 * Created
 */
export const zCreateUnityOfMeasureResponse = zUnityOfMeasureBasicDto;

export const zDeleteUnityOfMeasurePath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zDeleteUnityOfMeasureResponse = z.union([
  z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    }),
  z.string().regex(/^-?(?:0|[1-9]\d*)$/),
]);

export const zGetUnityOfMeasureByIdPath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zGetUnityOfMeasureByIdResponse = zUnityOfMeasureBasicDto;

export const zUpdateUnityOfMeasureBody = zUnityOfMeasureBasicDto;

export const zUpdateUnityOfMeasurePath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zUpdateUnityOfMeasureResponse = zUnityOfMeasureBasicDto;

export const zGetProductsByUnityOfMeasurePath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

export const zGetProductsByUnityOfMeasureQuery = z.object({
  PageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  PageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  SearchTerm: z.string().optional(),
});

/**
 * OK
 */
export const zGetProductsByUnityOfMeasureResponse = zPagedListOfProductBasicDto;

/**
 * OK
 */
export const zGetUnitsOfMeasureLookupResponse = z.array(zLookupDto);

export const zGetPurchasesQuery = z.object({
  PageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  PageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  SearchTerm: z.string().optional(),
});

/**
 * OK
 */
export const zGetPurchasesResponse = zPagedListOfPurchaseBasicDto;

export const zCreatePurchaseBody = zPurchaseCreateDto;

/**
 * Created
 */
export const zCreatePurchaseResponse = zPurchaseBasicDto;

export const zCancelPurchasePath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zCancelPurchaseResponse = z.union([
  z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    }),
  z.string().regex(/^-?(?:0|[1-9]\d*)$/),
]);

export const zGetPurchaseByIdPath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zGetPurchaseByIdResponse = zPurchaseExtendedDto;

export const zGetLotsByPurchasePath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

export const zGetLotsByPurchaseQuery = z.object({
  PageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  PageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  SearchTerm: z.string().optional(),
});

/**
 * OK
 */
export const zGetLotsByPurchaseResponse = zPagedListOfLotBasicDto;

export const zGetLotsQuery = z.object({
  PageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  PageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  SearchTerm: z.string().optional(),
});

/**
 * OK
 */
export const zGetLotsResponse = zPagedListOfLotBasicDto;

export const zGetLotByIdPath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zGetLotByIdResponse = zLotExtended;

export const zGetSalesQuery = z.object({
  PageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  PageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  SearchTerm: z.string().optional(),
});

/**
 * OK
 */
export const zGetSalesResponse = zPagedListOfSaleBasicDto;

export const zCreateSaleBody = zSaleCreateDto;

/**
 * Created
 */
export const zCreateSaleResponse = zSaleBasicDto;

export const zCancelSalePath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zCancelSaleResponse = z.union([
  z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    }),
  z.string().regex(/^-?(?:0|[1-9]\d*)$/),
]);

export const zGetSaleByIdPath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

/**
 * OK
 */
export const zGetSaleByIdResponse = zSaleBasicDto;

export const zGetSaleDetailsBySalePath = z.object({
  id: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
});

export const zGetSaleDetailsBySaleQuery = z.object({
  PageNumber: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  PageSize: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  SearchTerm: z.string().optional(),
});

/**
 * OK
 */
export const zGetSaleDetailsBySaleResponse = zPagedListOfSaleDetailsBasicDto;
