// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  cancelPurchase,
  cancelSale,
  createCategory,
  createProduct,
  createPurchase,
  createSale,
  createSupplier,
  createUnityOfMeasure,
  deleteCategory,
  deleteProduct,
  deleteSupplier,
  deleteUnityOfMeasure,
  getApiAuthManageInfo,
  getCategories,
  getCategoriesLookup,
  getCategoryById,
  getFinancialSummary,
  getLotById,
  getLots,
  getLotsByProduct,
  getLotsByPurchase,
  getProductById,
  getProducts,
  getProductsByCategory,
  getProductsByUnityOfMeasure,
  getProductsLookup,
  getPurchaseById,
  getPurchases,
  getPurchasesBySupplier,
  getRecentTransactions,
  getSaleById,
  getSaleDetailsBySale,
  getSales,
  getSupplierById,
  getSuppliers,
  getSuppliersLookup,
  getUnitsOfMeasure,
  getUnitsOfMeasureLookup,
  getUnityOfMeasureById,
  getUser,
  mapIdentityApiApiAuthConfirmEmail,
  type Options,
  postApiAuthForgotPassword,
  postApiAuthLogin,
  postApiAuthManage2Fa,
  postApiAuthManageInfo,
  postApiAuthRefresh,
  postApiAuthRegister,
  postApiAuthResendConfirmationEmail,
  postApiAuthResetPassword,
  updateCategory,
  updateProduct,
  updateSupplier,
  updateUnityOfMeasure,
} from "../sdk.gen";
import type {
  CancelPurchaseData,
  CancelPurchaseError,
  CancelPurchaseResponse,
  CancelSaleData,
  CancelSaleError,
  CancelSaleResponse,
  CreateCategoryData,
  CreateCategoryError,
  CreateCategoryResponse,
  CreateProductData,
  CreateProductError,
  CreateProductResponse,
  CreatePurchaseData,
  CreatePurchaseError,
  CreatePurchaseResponse,
  CreateSaleData,
  CreateSaleError,
  CreateSaleResponse,
  CreateSupplierData,
  CreateSupplierError,
  CreateSupplierResponse,
  CreateUnityOfMeasureData,
  CreateUnityOfMeasureError,
  CreateUnityOfMeasureResponse,
  DeleteCategoryData,
  DeleteCategoryError,
  DeleteCategoryResponse,
  DeleteProductData,
  DeleteProductError,
  DeleteProductResponse,
  DeleteSupplierData,
  DeleteSupplierError,
  DeleteSupplierResponse,
  DeleteUnityOfMeasureData,
  DeleteUnityOfMeasureError,
  DeleteUnityOfMeasureResponse,
  GetApiAuthManageInfoData,
  GetApiAuthManageInfoError,
  GetApiAuthManageInfoResponse,
  GetCategoriesData,
  GetCategoriesLookupData,
  GetCategoriesLookupResponse,
  GetCategoriesResponse,
  GetCategoryByIdData,
  GetCategoryByIdError,
  GetCategoryByIdResponse,
  GetFinancialSummaryData,
  GetFinancialSummaryResponse,
  GetLotByIdData,
  GetLotByIdError,
  GetLotByIdResponse,
  GetLotsByProductData,
  GetLotsByProductResponse,
  GetLotsByPurchaseData,
  GetLotsByPurchaseResponse,
  GetLotsData,
  GetLotsResponse,
  GetProductByIdData,
  GetProductByIdError,
  GetProductByIdResponse,
  GetProductsByCategoryData,
  GetProductsByCategoryResponse,
  GetProductsByUnityOfMeasureData,
  GetProductsByUnityOfMeasureResponse,
  GetProductsData,
  GetProductsLookupData,
  GetProductsLookupResponse,
  GetProductsResponse,
  GetPurchaseByIdData,
  GetPurchaseByIdError,
  GetPurchaseByIdResponse,
  GetPurchasesBySupplierData,
  GetPurchasesBySupplierResponse,
  GetPurchasesData,
  GetPurchasesResponse,
  GetRecentTransactionsData,
  GetRecentTransactionsResponse,
  GetSaleByIdData,
  GetSaleByIdError,
  GetSaleByIdResponse,
  GetSaleDetailsBySaleData,
  GetSaleDetailsBySaleResponse,
  GetSalesData,
  GetSalesResponse,
  GetSupplierByIdData,
  GetSupplierByIdError,
  GetSupplierByIdResponse,
  GetSuppliersData,
  GetSuppliersLookupData,
  GetSuppliersLookupResponse,
  GetSuppliersResponse,
  GetUnitsOfMeasureData,
  GetUnitsOfMeasureLookupData,
  GetUnitsOfMeasureLookupResponse,
  GetUnitsOfMeasureResponse,
  GetUnityOfMeasureByIdData,
  GetUnityOfMeasureByIdError,
  GetUnityOfMeasureByIdResponse,
  GetUserData,
  GetUserResponse,
  MapIdentityApiApiAuthConfirmEmailData,
  PostApiAuthForgotPasswordData,
  PostApiAuthForgotPasswordError,
  PostApiAuthLoginData,
  PostApiAuthLoginResponse,
  PostApiAuthManage2FaData,
  PostApiAuthManage2FaError,
  PostApiAuthManage2FaResponse,
  PostApiAuthManageInfoData,
  PostApiAuthManageInfoError,
  PostApiAuthManageInfoResponse,
  PostApiAuthRefreshData,
  PostApiAuthRefreshResponse,
  PostApiAuthRegisterData,
  PostApiAuthRegisterError,
  PostApiAuthResendConfirmationEmailData,
  PostApiAuthResetPasswordData,
  PostApiAuthResetPasswordError,
  UpdateCategoryData,
  UpdateCategoryError,
  UpdateCategoryResponse,
  UpdateProductData,
  UpdateProductError,
  UpdateProductResponse,
  UpdateSupplierData,
  UpdateSupplierError,
  UpdateSupplierResponse,
  UpdateUnityOfMeasureData,
  UpdateUnityOfMeasureError,
  UpdateUnityOfMeasureResponse,
} from "../types.gen";

export const postApiAuthRegisterMutation = (
  options?: Partial<Options<PostApiAuthRegisterData>>
): UseMutationOptions<
  unknown,
  PostApiAuthRegisterError,
  Options<PostApiAuthRegisterData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    PostApiAuthRegisterError,
    Options<PostApiAuthRegisterData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthRegister({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postApiAuthLoginMutation = (
  options?: Partial<Options<PostApiAuthLoginData>>
): UseMutationOptions<
  PostApiAuthLoginResponse,
  DefaultError,
  Options<PostApiAuthLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthLoginResponse,
    DefaultError,
    Options<PostApiAuthLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postApiAuthRefreshMutation = (
  options?: Partial<Options<PostApiAuthRefreshData>>
): UseMutationOptions<
  PostApiAuthRefreshResponse,
  DefaultError,
  Options<PostApiAuthRefreshData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthRefreshResponse,
    DefaultError,
    Options<PostApiAuthRefreshData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthRefresh({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const mapIdentityApiApiAuthConfirmEmailQueryKey = (
  options: Options<MapIdentityApiApiAuthConfirmEmailData>
) => createQueryKey("mapIdentityApiApiAuthConfirmEmail", options);

export const mapIdentityApiApiAuthConfirmEmailOptions = (
  options: Options<MapIdentityApiApiAuthConfirmEmailData>
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof mapIdentityApiApiAuthConfirmEmailQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await mapIdentityApiApiAuthConfirmEmail({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: mapIdentityApiApiAuthConfirmEmailQueryKey(options),
  });

export const postApiAuthResendConfirmationEmailMutation = (
  options?: Partial<Options<PostApiAuthResendConfirmationEmailData>>
): UseMutationOptions<
  unknown,
  DefaultError,
  Options<PostApiAuthResendConfirmationEmailData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<PostApiAuthResendConfirmationEmailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthResendConfirmationEmail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postApiAuthForgotPasswordMutation = (
  options?: Partial<Options<PostApiAuthForgotPasswordData>>
): UseMutationOptions<
  unknown,
  PostApiAuthForgotPasswordError,
  Options<PostApiAuthForgotPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    PostApiAuthForgotPasswordError,
    Options<PostApiAuthForgotPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthForgotPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postApiAuthResetPasswordMutation = (
  options?: Partial<Options<PostApiAuthResetPasswordData>>
): UseMutationOptions<
  unknown,
  PostApiAuthResetPasswordError,
  Options<PostApiAuthResetPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    PostApiAuthResetPasswordError,
    Options<PostApiAuthResetPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthResetPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postApiAuthManage2FaMutation = (
  options?: Partial<Options<PostApiAuthManage2FaData>>
): UseMutationOptions<
  PostApiAuthManage2FaResponse,
  PostApiAuthManage2FaError,
  Options<PostApiAuthManage2FaData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthManage2FaResponse,
    PostApiAuthManage2FaError,
    Options<PostApiAuthManage2FaData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthManage2Fa({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiAuthManageInfoQueryKey = (
  options?: Options<GetApiAuthManageInfoData>
) => createQueryKey("getApiAuthManageInfo", options);

export const getApiAuthManageInfoOptions = (
  options?: Options<GetApiAuthManageInfoData>
) =>
  queryOptions<
    GetApiAuthManageInfoResponse,
    GetApiAuthManageInfoError,
    GetApiAuthManageInfoResponse,
    ReturnType<typeof getApiAuthManageInfoQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAuthManageInfo({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiAuthManageInfoQueryKey(options),
  });

export const postApiAuthManageInfoMutation = (
  options?: Partial<Options<PostApiAuthManageInfoData>>
): UseMutationOptions<
  PostApiAuthManageInfoResponse,
  PostApiAuthManageInfoError,
  Options<PostApiAuthManageInfoData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthManageInfoResponse,
    PostApiAuthManageInfoError,
    Options<PostApiAuthManageInfoData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthManageInfo({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getUserQueryKey = (options?: Options<GetUserData>) =>
  createQueryKey("getUser", options);

export const getUserOptions = (options?: Options<GetUserData>) =>
  queryOptions<
    GetUserResponse,
    DefaultError,
    GetUserResponse,
    ReturnType<typeof getUserQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserQueryKey(options),
  });

export const getProductsQueryKey = (options: Options<GetProductsData>) =>
  createQueryKey("getProducts", options);

export const getProductsOptions = (options: Options<GetProductsData>) =>
  queryOptions<
    GetProductsResponse,
    DefaultError,
    GetProductsResponse,
    ReturnType<typeof getProductsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProducts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getProductsQueryKey(options),
  });

export const createProductMutation = (
  options?: Partial<Options<CreateProductData>>
): UseMutationOptions<
  CreateProductResponse,
  CreateProductError,
  Options<CreateProductData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateProductResponse,
    CreateProductError,
    Options<CreateProductData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createProduct({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteProductMutation = (
  options?: Partial<Options<DeleteProductData>>
): UseMutationOptions<
  DeleteProductResponse,
  DeleteProductError,
  Options<DeleteProductData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteProductResponse,
    DeleteProductError,
    Options<DeleteProductData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteProduct({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getProductByIdQueryKey = (options: Options<GetProductByIdData>) =>
  createQueryKey("getProductById", options);

export const getProductByIdOptions = (options: Options<GetProductByIdData>) =>
  queryOptions<
    GetProductByIdResponse,
    GetProductByIdError,
    GetProductByIdResponse,
    ReturnType<typeof getProductByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProductById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getProductByIdQueryKey(options),
  });

export const updateProductMutation = (
  options?: Partial<Options<UpdateProductData>>
): UseMutationOptions<
  UpdateProductResponse,
  UpdateProductError,
  Options<UpdateProductData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateProductResponse,
    UpdateProductError,
    Options<UpdateProductData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateProduct({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getLotsByProductQueryKey = (
  options: Options<GetLotsByProductData>
) => createQueryKey("getLotsByProduct", options);

export const getLotsByProductOptions = (
  options: Options<GetLotsByProductData>
) =>
  queryOptions<
    GetLotsByProductResponse,
    DefaultError,
    GetLotsByProductResponse,
    ReturnType<typeof getLotsByProductQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLotsByProduct({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getLotsByProductQueryKey(options),
  });

export const getProductsLookupQueryKey = (
  options?: Options<GetProductsLookupData>
) => createQueryKey("getProductsLookup", options);

export const getProductsLookupOptions = (
  options?: Options<GetProductsLookupData>
) =>
  queryOptions<
    GetProductsLookupResponse,
    DefaultError,
    GetProductsLookupResponse,
    ReturnType<typeof getProductsLookupQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProductsLookup({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getProductsLookupQueryKey(options),
  });

export const getCategoriesQueryKey = (options: Options<GetCategoriesData>) =>
  createQueryKey("getCategories", options);

export const getCategoriesOptions = (options: Options<GetCategoriesData>) =>
  queryOptions<
    GetCategoriesResponse,
    DefaultError,
    GetCategoriesResponse,
    ReturnType<typeof getCategoriesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCategories({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCategoriesQueryKey(options),
  });

export const createCategoryMutation = (
  options?: Partial<Options<CreateCategoryData>>
): UseMutationOptions<
  CreateCategoryResponse,
  CreateCategoryError,
  Options<CreateCategoryData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateCategoryResponse,
    CreateCategoryError,
    Options<CreateCategoryData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createCategory({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteCategoryMutation = (
  options?: Partial<Options<DeleteCategoryData>>
): UseMutationOptions<
  DeleteCategoryResponse,
  DeleteCategoryError,
  Options<DeleteCategoryData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteCategoryResponse,
    DeleteCategoryError,
    Options<DeleteCategoryData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteCategory({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getCategoryByIdQueryKey = (
  options: Options<GetCategoryByIdData>
) => createQueryKey("getCategoryById", options);

export const getCategoryByIdOptions = (options: Options<GetCategoryByIdData>) =>
  queryOptions<
    GetCategoryByIdResponse,
    GetCategoryByIdError,
    GetCategoryByIdResponse,
    ReturnType<typeof getCategoryByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCategoryById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCategoryByIdQueryKey(options),
  });

export const updateCategoryMutation = (
  options?: Partial<Options<UpdateCategoryData>>
): UseMutationOptions<
  UpdateCategoryResponse,
  UpdateCategoryError,
  Options<UpdateCategoryData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateCategoryResponse,
    UpdateCategoryError,
    Options<UpdateCategoryData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateCategory({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getProductsByCategoryQueryKey = (
  options: Options<GetProductsByCategoryData>
) => createQueryKey("getProductsByCategory", options);

export const getProductsByCategoryOptions = (
  options: Options<GetProductsByCategoryData>
) =>
  queryOptions<
    GetProductsByCategoryResponse,
    DefaultError,
    GetProductsByCategoryResponse,
    ReturnType<typeof getProductsByCategoryQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProductsByCategory({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getProductsByCategoryQueryKey(options),
  });

export const getCategoriesLookupQueryKey = (
  options?: Options<GetCategoriesLookupData>
) => createQueryKey("getCategoriesLookup", options);

export const getCategoriesLookupOptions = (
  options?: Options<GetCategoriesLookupData>
) =>
  queryOptions<
    GetCategoriesLookupResponse,
    DefaultError,
    GetCategoriesLookupResponse,
    ReturnType<typeof getCategoriesLookupQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCategoriesLookup({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCategoriesLookupQueryKey(options),
  });

export const getSuppliersQueryKey = (options: Options<GetSuppliersData>) =>
  createQueryKey("getSuppliers", options);

export const getSuppliersOptions = (options: Options<GetSuppliersData>) =>
  queryOptions<
    GetSuppliersResponse,
    DefaultError,
    GetSuppliersResponse,
    ReturnType<typeof getSuppliersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSuppliers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSuppliersQueryKey(options),
  });

export const createSupplierMutation = (
  options?: Partial<Options<CreateSupplierData>>
): UseMutationOptions<
  CreateSupplierResponse,
  CreateSupplierError,
  Options<CreateSupplierData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateSupplierResponse,
    CreateSupplierError,
    Options<CreateSupplierData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createSupplier({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteSupplierMutation = (
  options?: Partial<Options<DeleteSupplierData>>
): UseMutationOptions<
  DeleteSupplierResponse,
  DeleteSupplierError,
  Options<DeleteSupplierData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteSupplierResponse,
    DeleteSupplierError,
    Options<DeleteSupplierData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteSupplier({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getSupplierByIdQueryKey = (
  options: Options<GetSupplierByIdData>
) => createQueryKey("getSupplierById", options);

export const getSupplierByIdOptions = (options: Options<GetSupplierByIdData>) =>
  queryOptions<
    GetSupplierByIdResponse,
    GetSupplierByIdError,
    GetSupplierByIdResponse,
    ReturnType<typeof getSupplierByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSupplierById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSupplierByIdQueryKey(options),
  });

export const updateSupplierMutation = (
  options?: Partial<Options<UpdateSupplierData>>
): UseMutationOptions<
  UpdateSupplierResponse,
  UpdateSupplierError,
  Options<UpdateSupplierData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateSupplierResponse,
    UpdateSupplierError,
    Options<UpdateSupplierData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateSupplier({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getPurchasesBySupplierQueryKey = (
  options: Options<GetPurchasesBySupplierData>
) => createQueryKey("getPurchasesBySupplier", options);

export const getPurchasesBySupplierOptions = (
  options: Options<GetPurchasesBySupplierData>
) =>
  queryOptions<
    GetPurchasesBySupplierResponse,
    DefaultError,
    GetPurchasesBySupplierResponse,
    ReturnType<typeof getPurchasesBySupplierQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPurchasesBySupplier({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPurchasesBySupplierQueryKey(options),
  });

export const getSuppliersLookupQueryKey = (
  options?: Options<GetSuppliersLookupData>
) => createQueryKey("getSuppliersLookup", options);

export const getSuppliersLookupOptions = (
  options?: Options<GetSuppliersLookupData>
) =>
  queryOptions<
    GetSuppliersLookupResponse,
    DefaultError,
    GetSuppliersLookupResponse,
    ReturnType<typeof getSuppliersLookupQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSuppliersLookup({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSuppliersLookupQueryKey(options),
  });

export const getUnitsOfMeasureQueryKey = (
  options: Options<GetUnitsOfMeasureData>
) => createQueryKey("getUnitsOfMeasure", options);

export const getUnitsOfMeasureOptions = (
  options: Options<GetUnitsOfMeasureData>
) =>
  queryOptions<
    GetUnitsOfMeasureResponse,
    DefaultError,
    GetUnitsOfMeasureResponse,
    ReturnType<typeof getUnitsOfMeasureQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUnitsOfMeasure({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUnitsOfMeasureQueryKey(options),
  });

export const createUnityOfMeasureMutation = (
  options?: Partial<Options<CreateUnityOfMeasureData>>
): UseMutationOptions<
  CreateUnityOfMeasureResponse,
  CreateUnityOfMeasureError,
  Options<CreateUnityOfMeasureData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateUnityOfMeasureResponse,
    CreateUnityOfMeasureError,
    Options<CreateUnityOfMeasureData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUnityOfMeasure({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteUnityOfMeasureMutation = (
  options?: Partial<Options<DeleteUnityOfMeasureData>>
): UseMutationOptions<
  DeleteUnityOfMeasureResponse,
  DeleteUnityOfMeasureError,
  Options<DeleteUnityOfMeasureData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteUnityOfMeasureResponse,
    DeleteUnityOfMeasureError,
    Options<DeleteUnityOfMeasureData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteUnityOfMeasure({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getUnityOfMeasureByIdQueryKey = (
  options: Options<GetUnityOfMeasureByIdData>
) => createQueryKey("getUnityOfMeasureById", options);

export const getUnityOfMeasureByIdOptions = (
  options: Options<GetUnityOfMeasureByIdData>
) =>
  queryOptions<
    GetUnityOfMeasureByIdResponse,
    GetUnityOfMeasureByIdError,
    GetUnityOfMeasureByIdResponse,
    ReturnType<typeof getUnityOfMeasureByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUnityOfMeasureById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUnityOfMeasureByIdQueryKey(options),
  });

export const updateUnityOfMeasureMutation = (
  options?: Partial<Options<UpdateUnityOfMeasureData>>
): UseMutationOptions<
  UpdateUnityOfMeasureResponse,
  UpdateUnityOfMeasureError,
  Options<UpdateUnityOfMeasureData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateUnityOfMeasureResponse,
    UpdateUnityOfMeasureError,
    Options<UpdateUnityOfMeasureData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateUnityOfMeasure({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getProductsByUnityOfMeasureQueryKey = (
  options: Options<GetProductsByUnityOfMeasureData>
) => createQueryKey("getProductsByUnityOfMeasure", options);

export const getProductsByUnityOfMeasureOptions = (
  options: Options<GetProductsByUnityOfMeasureData>
) =>
  queryOptions<
    GetProductsByUnityOfMeasureResponse,
    DefaultError,
    GetProductsByUnityOfMeasureResponse,
    ReturnType<typeof getProductsByUnityOfMeasureQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProductsByUnityOfMeasure({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getProductsByUnityOfMeasureQueryKey(options),
  });

export const getUnitsOfMeasureLookupQueryKey = (
  options?: Options<GetUnitsOfMeasureLookupData>
) => createQueryKey("getUnitsOfMeasureLookup", options);

export const getUnitsOfMeasureLookupOptions = (
  options?: Options<GetUnitsOfMeasureLookupData>
) =>
  queryOptions<
    GetUnitsOfMeasureLookupResponse,
    DefaultError,
    GetUnitsOfMeasureLookupResponse,
    ReturnType<typeof getUnitsOfMeasureLookupQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUnitsOfMeasureLookup({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUnitsOfMeasureLookupQueryKey(options),
  });

export const getPurchasesQueryKey = (options: Options<GetPurchasesData>) =>
  createQueryKey("getPurchases", options);

export const getPurchasesOptions = (options: Options<GetPurchasesData>) =>
  queryOptions<
    GetPurchasesResponse,
    DefaultError,
    GetPurchasesResponse,
    ReturnType<typeof getPurchasesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPurchases({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPurchasesQueryKey(options),
  });

export const createPurchaseMutation = (
  options?: Partial<Options<CreatePurchaseData>>
): UseMutationOptions<
  CreatePurchaseResponse,
  CreatePurchaseError,
  Options<CreatePurchaseData>
> => {
  const mutationOptions: UseMutationOptions<
    CreatePurchaseResponse,
    CreatePurchaseError,
    Options<CreatePurchaseData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createPurchase({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const cancelPurchaseMutation = (
  options?: Partial<Options<CancelPurchaseData>>
): UseMutationOptions<
  CancelPurchaseResponse,
  CancelPurchaseError,
  Options<CancelPurchaseData>
> => {
  const mutationOptions: UseMutationOptions<
    CancelPurchaseResponse,
    CancelPurchaseError,
    Options<CancelPurchaseData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await cancelPurchase({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getPurchaseByIdQueryKey = (
  options: Options<GetPurchaseByIdData>
) => createQueryKey("getPurchaseById", options);

export const getPurchaseByIdOptions = (options: Options<GetPurchaseByIdData>) =>
  queryOptions<
    GetPurchaseByIdResponse,
    GetPurchaseByIdError,
    GetPurchaseByIdResponse,
    ReturnType<typeof getPurchaseByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPurchaseById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPurchaseByIdQueryKey(options),
  });

export const getLotsByPurchaseQueryKey = (
  options: Options<GetLotsByPurchaseData>
) => createQueryKey("getLotsByPurchase", options);

export const getLotsByPurchaseOptions = (
  options: Options<GetLotsByPurchaseData>
) =>
  queryOptions<
    GetLotsByPurchaseResponse,
    DefaultError,
    GetLotsByPurchaseResponse,
    ReturnType<typeof getLotsByPurchaseQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLotsByPurchase({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getLotsByPurchaseQueryKey(options),
  });

export const getLotsQueryKey = (options: Options<GetLotsData>) =>
  createQueryKey("getLots", options);

export const getLotsOptions = (options: Options<GetLotsData>) =>
  queryOptions<
    GetLotsResponse,
    DefaultError,
    GetLotsResponse,
    ReturnType<typeof getLotsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLots({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getLotsQueryKey(options),
  });

export const getLotByIdQueryKey = (options: Options<GetLotByIdData>) =>
  createQueryKey("getLotById", options);

export const getLotByIdOptions = (options: Options<GetLotByIdData>) =>
  queryOptions<
    GetLotByIdResponse,
    GetLotByIdError,
    GetLotByIdResponse,
    ReturnType<typeof getLotByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLotById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getLotByIdQueryKey(options),
  });

export const getSalesQueryKey = (options: Options<GetSalesData>) =>
  createQueryKey("getSales", options);

export const getSalesOptions = (options: Options<GetSalesData>) =>
  queryOptions<
    GetSalesResponse,
    DefaultError,
    GetSalesResponse,
    ReturnType<typeof getSalesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSales({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSalesQueryKey(options),
  });

export const createSaleMutation = (
  options?: Partial<Options<CreateSaleData>>
): UseMutationOptions<
  CreateSaleResponse,
  CreateSaleError,
  Options<CreateSaleData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateSaleResponse,
    CreateSaleError,
    Options<CreateSaleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createSale({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const cancelSaleMutation = (
  options?: Partial<Options<CancelSaleData>>
): UseMutationOptions<
  CancelSaleResponse,
  CancelSaleError,
  Options<CancelSaleData>
> => {
  const mutationOptions: UseMutationOptions<
    CancelSaleResponse,
    CancelSaleError,
    Options<CancelSaleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await cancelSale({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getSaleByIdQueryKey = (options: Options<GetSaleByIdData>) =>
  createQueryKey("getSaleById", options);

export const getSaleByIdOptions = (options: Options<GetSaleByIdData>) =>
  queryOptions<
    GetSaleByIdResponse,
    GetSaleByIdError,
    GetSaleByIdResponse,
    ReturnType<typeof getSaleByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSaleById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSaleByIdQueryKey(options),
  });

export const getSaleDetailsBySaleQueryKey = (
  options: Options<GetSaleDetailsBySaleData>
) => createQueryKey("getSaleDetailsBySale", options);

export const getSaleDetailsBySaleOptions = (
  options: Options<GetSaleDetailsBySaleData>
) =>
  queryOptions<
    GetSaleDetailsBySaleResponse,
    DefaultError,
    GetSaleDetailsBySaleResponse,
    ReturnType<typeof getSaleDetailsBySaleQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSaleDetailsBySale({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSaleDetailsBySaleQueryKey(options),
  });

export const getFinancialSummaryQueryKey = (
  options: Options<GetFinancialSummaryData>
) => createQueryKey("getFinancialSummary", options);

export const getFinancialSummaryOptions = (
  options: Options<GetFinancialSummaryData>
) =>
  queryOptions<
    GetFinancialSummaryResponse,
    DefaultError,
    GetFinancialSummaryResponse,
    ReturnType<typeof getFinancialSummaryQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFinancialSummary({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFinancialSummaryQueryKey(options),
  });

export const getRecentTransactionsQueryKey = (
  options?: Options<GetRecentTransactionsData>
) => createQueryKey("getRecentTransactions", options);

export const getRecentTransactionsOptions = (
  options?: Options<GetRecentTransactionsData>
) =>
  queryOptions<
    GetRecentTransactionsResponse,
    DefaultError,
    GetRecentTransactionsResponse,
    ReturnType<typeof getRecentTransactionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRecentTransactions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRecentTransactionsQueryKey(options),
  });
